// Mock of the LLM provider, the tuning parameters and the vision sidecar. A representative subset of the 72
// parameters (the real list is generated by the BE from env.ts / tuning-definitions); keys and defaults
// follow zalo-agent. Secrets never come back: only the masked tail of an API key.
import { bodyOf, fail, type Reply, type Router, type Schemas } from "../core";

type S = Schemas;
type TuningValue = S["TuningItem"]["value"];

const maskKey = (key: string): string => (key ? `••••${key.slice(-4)}` : "");

const provider = {
  provider: "openai-compatible" as S["LlmProviderKind"],
  base_url: "https://openrouter.ai/api/v1",
  model: "qwen3-8b",
  api_key: "",
};

function providerOut(): S["LlmSettingsOut"] {
  return {
    provider: provider.provider,
    base_url: provider.base_url,
    model: provider.model,
    api_key_masked: maskKey(provider.api_key),
    has_override: true,
  };
}

export const vision = {
  enabled: false,
  provider: "openai-compatible" as S["LlmProviderKind"] | null,
  base_url: "",
  model: "",
  api_key: "",
};

export function visionOut(): S["VisionSettingsOut"] {
  return {
    enabled: vision.enabled,
    provider: vision.provider,
    base_url: vision.base_url,
    model: vision.model,
    api_key_masked: maskKey(vision.api_key),
    has_override: Boolean(vision.base_url || vision.model),
  };
}

// ------------------------------------------------------------------ tuning

const GROUPS: S["TuningGroup"][] = [
  {
    id: "providers",
    title: "Nhà cung cấp LLM",
    hint: "Model trả lời khách. Thiếu mục này thì trợ lý không trả lời được tin nào.",
    nav_hint: "Model, base URL, API key",
  },
  {
    id: "agent",
    title: "Agent và model",
    hint: "Số bước, mức suy nghĩ và ngân sách token của mỗi lượt trả lời.",
    nav_hint: "Bước, token, suy nghĩ",
  },
  {
    id: "memory",
    title: "Trí nhớ và ngữ cảnh",
    hint: "Bao nhiêu tin nhắn cũ được giữ lại và tóm tắt cho mỗi cuộc trò chuyện.",
    nav_hint: "Lịch sử, tóm tắt",
  },
  {
    id: "knowledge",
    title: "Kho tri thức",
    hint: "Giới hạn khi nạp và xử lý tài liệu.",
    nav_hint: "Dung lượng, số lần thử",
  },
  {
    id: "scheduler",
    title: "Tin chủ động và lịch",
    hint: "Trần tin chủ động mỗi ngày và khoảng cách giữa các tin.",
    nav_hint: "Trần ngày, khoảng cách",
  },
  {
    id: "general",
    title: "Chung",
    hint: "Múi giờ, ghi vết và thời hạn lưu dữ liệu.",
    nav_hint: "Múi giờ, trace, lưu trữ",
  },
];

type Def = Omit<S["TuningItem"], "value" | "overridden">;

const DEFS: Def[] = [
  {
    key: "LLM_CONTEXT_WINDOW",
    group: "agent",
    kind: "number",
    label: "Cửa sổ ngữ cảnh",
    hint: "Trần token cho phần VÀO của một lần gọi model.",
    default: 128000,
    min: 8000,
    max: 2000000,
    presets: [32000, 128000, 200000, 256000, 1000000, 1050000, 2000000],
    token_estimate_hint: false,
  },
  {
    key: "LLM_MAX_OUTPUT_TOKENS",
    group: "agent",
    kind: "number",
    label: "Trần token viết ra",
    hint: "Số token tối đa model viết ra trong một bước.",
    default: 16384,
    min: 1024,
    max: 128000,
    presets: [4096, 8192, 16384, 32000, 64000, 128000],
    token_estimate_hint: false,
  },
  {
    key: "LLM_REASONING_EFFORT",
    group: "agent",
    kind: "select",
    label: "Mức suy nghĩ mặc định",
    hint: "Agent nào không đặt riêng sẽ theo mức này.",
    default: "off",
    options: ["off", "low", "medium", "high", "xhigh"],
    token_estimate_hint: false,
  },
  {
    key: "AGENT_MAX_STEPS",
    group: "agent",
    kind: "number",
    label: "Số bước tối đa mỗi lượt",
    hint: "Một bước là một lần model gọi công cụ rồi đọc kết quả.",
    default: 8,
    min: 1,
    max: 30,
    token_estimate_hint: false,
  },
  {
    key: "HISTORY_MAX_MESSAGES_PER_THREAD",
    group: "memory",
    kind: "number",
    label: "Tin nhắn giữ lại mỗi cuộc trò chuyện",
    hint: "Quá số này tin cũ nhất bị tóm tắt rồi xóa.",
    default: 200,
    min: 20,
    max: 2000,
    token_estimate_hint: false,
  },
  {
    key: "SUMMARY_ENABLED",
    group: "memory",
    kind: "boolean",
    label: "Tóm tắt cuộn",
    hint: "Tóm tắt tin cũ để giữ ngữ cảnh mà không tốn token.",
    default: true,
    token_estimate_hint: false,
  },
  {
    key: "DOCUMENT_MAX_CHARS",
    group: "memory",
    kind: "number",
    label: "Trần ký tự tài liệu tạo ra",
    hint: "Độ dài tối đa nội dung một tệp do bot tạo.",
    default: 20000,
    min: 1000,
    max: 60000,
    token_estimate_hint: true,
  },
  {
    key: "KB_MAX_FILE_MB",
    group: "knowledge",
    kind: "number",
    label: "Dung lượng tối đa mỗi tệp (MB)",
    hint: "Tệp lớn hơn bị từ chối ngay khi tải lên.",
    default: 7,
    min: 1,
    max: 50,
    token_estimate_hint: false,
  },
  {
    key: "KB_MAX_ATTEMPTS",
    group: "knowledge",
    kind: "number",
    label: "Số lần thử lại một nguồn",
    hint: "Quá số này nguồn chuyển sang Hỏng cho tới khi bấm Xử lý lại.",
    default: 3,
    min: 1,
    max: 10,
    token_estimate_hint: false,
  },
  {
    key: "SCHEDULER_MAX_PROACTIVE_PER_DAY",
    group: "scheduler",
    kind: "number",
    label: "Trần tin chủ động mỗi ngày",
    hint: "Theo từng cuộc trò chuyện (staff_assistant) hoặc từng bệnh nhân (patient_channel).",
    default: 10,
    min: 1,
    max: 100,
    token_estimate_hint: false,
  },
  {
    key: "SCHEDULER_MIN_GAP_SECONDS",
    group: "scheduler",
    kind: "number",
    label: "Khoảng cách tối thiểu giữa hai tin (giây)",
    hint: "Tránh gửi dồn dập nhiều tin liên tiếp.",
    default: 20,
    min: 0,
    max: 600,
    token_estimate_hint: false,
  },
  {
    key: "BOT_TIMEZONE",
    group: "general",
    kind: "text",
    label: "Múi giờ",
    hint: "Ngày, giờ gửi và trần mỗi ngày tính theo múi giờ này.",
    default: "Asia/Ho_Chi_Minh",
    token_estimate_hint: false,
  },
  {
    key: "AGENT_TRACE_ENABLED",
    group: "general",
    kind: "boolean",
    label: "Ghi vết từng bước agent",
    hint: "Cần để xem trang Trace. Vết có thể chứa nội dung tin nhắn.",
    default: true,
    token_estimate_hint: false,
  },
  {
    key: "AGENT_TRACE_RETENTION_DAYS",
    group: "general",
    kind: "number",
    label: "Giữ vết (ngày)",
    hint: "Quá hạn vết bị xóa. Chủ phòng khám quyết định thời hạn này.",
    default: 30,
    min: 1,
    max: 365,
    token_estimate_hint: false,
  },
  {
    key: "MEDIA_RETENTION_DAYS",
    group: "general",
    kind: "number",
    label: "Giữ ảnh và tệp (ngày)",
    hint: "Thời hạn lưu ảnh khách gửi. Chủ phòng khám quyết định.",
    default: 30,
    min: 1,
    max: 365,
    token_estimate_hint: false,
  },
];

const overrides = new Map<string, TuningValue>();

function tuningOut(): S["TuningOut"] {
  return {
    groups: GROUPS,
    items: DEFS.map((d) => ({
      ...d,
      value: overrides.get(d.key) ?? d.default,
      overridden: overrides.has(d.key),
    })),
  };
}

function validate(def: Def, value: TuningValue): string | null {
  if (def.kind === "number") {
    if (typeof value !== "number" || !Number.isFinite(value)) return `${def.label}: nhập một số.`;
    if (def.min != null && value < def.min) return `${def.label}: tối thiểu ${def.min}.`;
    if (def.max != null && value > def.max) return `${def.label}: tối đa ${def.max}.`;
  }
  if (def.kind === "select" && !def.options?.includes(String(value)))
    return `${def.label}: giá trị không hợp lệ.`;
  return null;
}

export function register(r: Router): void {
  r.get("/api/v1/admin/model/provider", "admin.model", (): Reply => ({ body: providerOut() }));

  r.patch("/api/v1/admin/model/provider", "admin.model", (ctx): Reply => {
    const input = bodyOf<S["LlmSettingsUpdate"]>(ctx);
    if (input.provider) provider.provider = input.provider;
    if (input.base_url !== undefined) provider.base_url = input.base_url ?? "";
    if (input.model !== undefined && input.model !== null) provider.model = input.model;
    if (input.api_key) provider.api_key = input.api_key;
    return { body: providerOut() };
  });

  r.delete("/api/v1/admin/model/provider", "admin.model", (): Reply => {
    Object.assign(provider, { base_url: "", model: "", api_key: "" });
    return { body: providerOut() };
  });

  r.post("/api/v1/admin/model/provider/test", "admin.model", (): Reply => {
    const body: S["LlmTestResult"] = provider.model
      ? { ok: true, reply: "Xin chào, tôi đã sẵn sàng." }
      : { ok: false, error: "Chưa cấu hình model." };
    return { body };
  });

  r.get("/api/v1/admin/model/tuning", "admin.model", (): Reply => ({ body: tuningOut() }));

  r.patch("/api/v1/admin/model/tuning", "admin.model", (ctx): Reply => {
    const { values } = bodyOf<S["TuningUpdate"]>(ctx);
    const entries = Object.entries(values);
    entries.forEach(([key, value]) => {
      const def = DEFS.find((d) => d.key === key);
      if (!def) fail(422, "validation_failed", `Tham số lạ: ${key}`);
      if (value === null) return;
      const problem = validate(def, value);
      if (problem) fail(422, "validation_failed", problem);
    });
    entries.forEach(([key, value]) => {
      if (value === null) overrides.delete(key);
      else overrides.set(key, value);
    });
    return { body: tuningOut() };
  });

  r.delete("/api/v1/admin/model/tuning", "admin.model", (): Reply => {
    overrides.clear();
    return { status: 204 };
  });

  r.get("/api/v1/admin/model/vision", "admin.model", (): Reply => ({ body: visionOut() }));

  r.patch("/api/v1/admin/model/vision", "admin.model", (ctx): Reply => {
    const input = bodyOf<S["VisionSettingsUpdate"]>(ctx);
    if (input.enabled !== undefined && input.enabled !== null) vision.enabled = input.enabled;
    if (input.provider) vision.provider = input.provider;
    if (input.base_url !== undefined) vision.base_url = input.base_url ?? "";
    if (input.model !== undefined) vision.model = input.model ?? "";
    if (input.api_key) vision.api_key = input.api_key;
    return { body: visionOut() };
  });

  r.delete("/api/v1/admin/model/vision/sidecar", "admin.model", (): Reply => {
    Object.assign(vision, { enabled: false, base_url: "", model: "", api_key: "" });
    return { status: 204 };
  });
}
