// Builds design-specs/INDEX.md, the hub that joins the app canvas (82 screens), the web canvases (old web + Next.js-only)
// and the Design System. Used by design-specs.cjs (indexMarkdown) and by unify-index.cjs. Pure function of committed files:
//   app model            design-specs/index.json (passed in by the caller)
//   web ids + app refs   design-specs/web/index.json (generated from inventory.json; `app_canvas` = app ids)
//   WI reasons           design-specs/web/notes.json -> served_by
//   Design System        design-system/ (file list and counts)
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '../../../../..');
const SPECS = path.join(ROOT, 'design-specs');
const WEB = path.join(SPECS, 'web');
const DS = path.join(ROOT, 'design-system');

const readJson = (p) => JSON.parse(fs.readFileSync(p, 'utf8').replace(/^﻿/, ''));
const enc = (rel) => rel.split('/').map((s) => encodeURIComponent(s).replace(/\(/g, '%28').replace(/\)/g, '%29')).join('/');
const link = (text, rel) => `[${text}](${enc(rel)})`;
const cell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');

const WEB_CANVAS_OLD = 'Pema Web redesign canvas/Pema Web.dc.html';
const WEB_CANVAS_NEXT = 'Pema Web redesign canvas/Pema Web (Next.js).dc.html';
const WEB_CANVAS_BLOCKS = 'Pema Web redesign canvas/Pema Web blocks.dc.html';

function loadWeb() {
  const index = readJson(path.join(WEB, 'index.json'));
  const notes = readJson(path.join(WEB, 'notes.json'));
  return { index, servedBy: notes.served_by || { reasons: {} } };
}

function dsFacts() {
  const comp = path.join(DS, 'components');
  const pages = fs.existsSync(comp) ? fs.readdirSync(comp).filter((f) => f.endsWith('.md') && f !== 'INDEX.md') : [];
  let tokens = null;
  try {
    tokens = readJson(path.join(DS, 'tokens.json'));
  } catch {
    tokens = null;
  }
  return { components: pages.length, tokens };
}

/** App id -> web ids that cite it in `app_canvas`. */
function reverseMap(webScreens) {
  const map = new Map();
  for (const w of webScreens) for (const a of w.app_canvas || []) (map.get(a) || map.set(a, []).get(a)).push(w.id);
  return map;
}

const webLink = (id) => link(id, `web/screens/${id}.md`);
const appLink = (id) => link(id, `screens/${id}.md`);

function hubMarkdown(model) {
  const { index, servedBy } = loadWeb();
  const web = index.screens;
  const rev = reverseMap(web);
  const groupName = new Map(index.groups.map((g) => [g.code, g.name]));
  const ds = dsFacts();
  const old = web.filter((w) => /^W[A-I]\d+$/.test(w.id));
  const next = web.filter((w) => /^W[J-L]\d+$/.test(w.id));
  const wi = web.filter((w) => w.group === 'WI');
  const withApp = web.filter((w) => (w.app_canvas || []).length).length;
  const appWithWeb = model.screens.filter((s) => (rev.get(s.id) || []).length).length;
  const out = [];
  const p = (...l) => out.push(...l);

  p('<!-- Generated by .claude/skills/pema-web-design/scripts/lib/hub.cjs (run through design-specs.cjs or unify-index.cjs). Edit design-specs/web/notes.json (served_by), inventory or the catalog, not this file. -->');
  p('# Design hub: app, web, Design System', '');
  p(`One page to move between the three design layers of Pema. App canvas: ${model.screens.length} screens (A1 … K3). Web canvases: ${web.length} screens (${old.length} old-web ids WA … WI, ${next.length} Next.js-only ids WJ … WL). Design System: ${ds.components} component pages, one token file.`, '');
  p('| Layer | Start here | Specs | Canvas file |', '|---|---|---|---|');
  p(`| App (KMP, mobile) | [App](#1-app-${model.screens.length}) | \`screens/<ID>.md\` | \`${model.canvas}\` |`);
  p(`| Web, old (Clinic Web, Finance, Patient Mobile) | [Web](#2-web-${web.length}) | \`web/screens/<ID>.md\` | ${link(WEB_CANVAS_OLD.split('/').pop(), '../' + WEB_CANVAS_OLD)} |`);
  p(`| Web, Next.js-only (agent admin, care agent, sign-in, shell, templates) | [Web](#2-web-${web.length}) | \`web/screens/<ID>.md\` | ${link(WEB_CANVAS_NEXT.split('/').pop(), '../' + WEB_CANVAS_NEXT)} |`);
  p(`| Design System | [Design System](#3-design-system) | \`design-system/components/<block>.md\` | blocks: ${link(WEB_CANVAS_BLOCKS.split('/').pop(), '../' + WEB_CANVAS_BLOCKS)} |`, '');
  p('How the ids relate:', '');
  p('- An app id (A1 … K3) and a web id (WA1 … WL19) are two designs of the same thing when the web id lists the app id in its `App canvas` column (`app_canvas` in `web/inventory.json`; `—` = no app counterpart, never a filter). The App table below carries the reverse map, so the lookup works in both directions.');
  p(`- ${withApp} of ${web.length} web ids cite at least one app id; ${appWithWeb} of ${model.screens.length} app ids are cited by at least one web id.`);
  p('- Ids are frozen. Never renumber; new ids are appended to the end of their group.');
  p('- The old web is the reference for behaviour, the app canvas for look. The Next.js-only ids (WJ, WK, WL) have no old-web or app original.', '');

  // 1. App
  p(`## 1. App (${model.screens.length})`, '');
  p(`Canvas: \`${model.canvas}\` (${model.canvasHash}). Specs: \`screens/<ID>.md\`. Last column = web ids that cite the app screen (reverse map).`, '');
  p('| Code | Screen | Logic source | KMP composable | Module | Ported | Web screens |', '|---|---|---|---|---|---|---|');
  for (const s of model.screens) {
    const ids = rev.get(s.id) || [];
    p(`| ${appLink(s.id)} | ${cell(s.name)} | ${s.source.kind === 'web' ? 'web' : 'KMP'} | ${s.kmp.composable ? `\`${s.kmp.composable}\`` : '—'} | ${s.kmp.module || '—'} | ${s.status === 'ported' ? '✓' : '—'} | ${ids.length ? ids.map(webLink).join(', ') : '—'} |`);
  }
  p('');

  // 2. Web
  p(`## 2. Web (${web.length})`, '');
  p(`Inventory: \`web/inventory.json\`. Per-screen specs: \`web/screens/<ID>.md\`. Full index with snapshot counts: [web/INDEX.md](web/INDEX.md). Block manual: [web/BLOCKS.md](web/BLOCKS.md).`, '');
  p('### 2.1 Groups', '');
  p('| Group | Name | Screens | Canvas file | With app counterpart | Next.js status |', '|---|---|---|---|---|---|');
  for (const g of index.groups) {
    const ws = web.filter((w) => w.group === g.code);
    const file = /^W[J-L]$/.test(g.code) ? WEB_CANVAS_NEXT : WEB_CANVAS_OLD;
    const st = new Map();
    for (const w of ws) st.set(w.next_status, (st.get(w.next_status) || 0) + 1);
    const stText = [...st].map(([k, v]) => `${k} ${v}`).join(', ');
    p(`| ${g.code} | ${cell(g.name)} | ${ws.length} | ${link(file.split('/').pop(), '../' + file)} | ${ws.filter((w) => (w.app_canvas || []).length).length} | ${cell(stText)} |`);
  }
  p('');

  p('### 2.2 Patient Mobile web (WI): served by KMP/Zalo', '');
  p(`${servedBy.scope || ''}`, '');
  p(`**Revisit when the clinic has a Zalo OA.** ${servedBy.revisit || ''}`, '');
  p('| Code | Screen | Status | App canvas | Reason |', '|---|---|---|---|---|');
  for (const w of wi) {
    const apps = (w.app_canvas || []).length ? w.app_canvas.map(appLink).join(', ') : '—';
    p(`| ${webLink(w.id)} | ${cell(w.name)} | ${cell(w.next_status)} | ${apps} | ${cell((servedBy.reasons || {})[w.id] || '')} |`);
  }
  p('');

  const sect = [
    ['2.3', `Old web, Clinic Web and Finance (WA … WH)`, old.filter((w) => w.group !== 'WI')],
    ['2.4', 'Next.js-only (WJ … WL)', next],
  ];
  for (const [num, title, rows] of sect) {
    p(`### ${num} ${title} (${rows.length})`, '');
    p('| Code | Screen | Kind | Group | Next.js route | Next.js status | App canvas |', '|---|---|---|---|---|---|---|');
    for (const w of rows) {
      const apps = (w.app_canvas || []).length ? w.app_canvas.map(appLink).join(', ') : '—';
      p(`| ${webLink(w.id)} | ${cell(w.name)} | ${w.kind} | ${w.group} ${cell(groupName.get(w.group))} | ${w.next_route ? `\`${cell(w.next_route)}\`` : '—'} | ${cell(w.next_status)} | ${apps} |`);
    }
    p('');
  }

  // 3. Design System
  p('## 3. Design System', '');
  p(`Source in the repo: \`design-system/\` (${ds.components} component pages, one \`tokens.json\`). Both web canvases and the blocks canvas point to it. Publishing to claude.ai/design is deferred.`, '');
  p('| What | File |', '|---|---|');
  p(`| Overview, change rule, commands | ${link('design-system/README.md', '../design-system/README.md')} |`);
  p(`| Tokens (single source of values) | ${link('design-system/tokens.json', '../design-system/tokens.json')} |`);
  p(`| Colour roles, light and dark, contrast | ${link('design-system/colors.md', '../design-system/colors.md')} |`);
  p(`| Type scale | ${link('design-system/typography.md', '../design-system/typography.md')} |`);
  p(`| Spacing, radius, elevation, frame sizes | ${link('design-system/spacing-radius-elevation.md', '../design-system/spacing-radius-elevation.md')} |`);
  p(`| Components: block, \`src/ui\` component, KMP \`core:ui\` composable (${ds.components} pages) | ${link('design-system/components/INDEX.md', '../design-system/components/INDEX.md')} |`);
  p(`| Web canvas blocks and how often screens use them | ${link('web/BLOCKS.md', 'web/BLOCKS.md')} |`);
  p(`| App canvas blocks to Compose | ${link('BLOCKS.md', 'BLOCKS.md')} |`, '');

  // 4. Canonical skill
  p('## 4. Keeping the canvases in step', '');
  p('- **Canonical skill: `pema-web-design`** (`.claude/skills/pema-web-design/SKILL.md`). The Next.js front end is the product, so one skill covers the web canvases, the specs, the change log (`web-design-changes.md`) and this hub.');
  p('- `pema-web-to-canvas` is app-only (the app canvas from web changes, log `web-changes.md`); `pema-canvas-to-kmp-compose` builds the app from the app canvas.');
  p('', '## Regenerate', '');
  p('```', 'node .claude/skills/pema-canvas-to-kmp-compose/scripts/design-specs.cjs            # app specs and this file', 'node .claude/skills/pema-canvas-to-kmp-compose/scripts/design-specs.cjs --check', 'node .claude/skills/pema-web-design/scripts/unify-index.cjs --check             # links, counts, every WI row mapped', '```', '');
  return out.join('\n');
}

module.exports = { hubMarkdown, loadWeb, reverseMap, ROOT, SPECS, WEB, DS, WEB_CANVAS_OLD, WEB_CANVAS_NEXT, WEB_CANVAS_BLOCKS };
