# ported from: src/video/thong-tin-video.ts
"""Common data shape that EVERY video source must return.

WHY A SEPARATE FILE: the two sources (TikWM and yt-dlp) return completely different JSON, but the layer above
may see only ONE shape. If the layer above read each source's raw JSON itself, adding a third source would
mean editing the whole call chain.

zca-js ``sendVideo`` demands ALL of ``videoUrl``, ``thumbnailUrl``, ``duration``, ``width``, ``height``, so a
source missing a field must make it up at the source layer, not push ``None`` upward.

Forced deviation: TypeScript object types become frozen dataclasses; the two discriminated unions
(``KetQuaNguon``) become two dataclasses with a ``Literal`` ``ok`` so pyright narrows on ``.ok``.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from pema.video.whitelist_nguon_video import NenTangVideo

TenNguonVideo = Literal["tikwm", "yt-dlp"]


@dataclass(frozen=True)
class ThongTinVideo:
    video_url: str
    """Direct play URL, watermark ALREADY removed."""
    thumbnail_url: str
    """Cover image: ``sendVideo`` requires it."""
    duration_ms: int
    """Milliseconds. ``sendVideo`` takes ms while sources usually return SECONDS: converted at the source
    layer."""
    width: int
    height: int
    file_size: int | None
    """Bytes. ``None`` when the source does not say: the layer above must cope."""
    tac_gia: str | None
    """Author name. USED ONLY to name the temp file, NOT given to the model.

    This is a FREE string the video poster chose (yt-dlp ``uploader``/``channel`` is a display name). It was
    shortened at the source layer, but do not rely on that: the place that uses it (``gui_video_qua_zalo``)
    filters one more layer.

    Putting it into the sentence the tool returns to the model, or into the history, opens an instruction
    injection path, and that path is DURABLE because history is re-read on every later turn. It was once like
    that, and was removed."""
    nguon: TenNguonVideo
    """Which source got it: logged, and told to the user when the fallback had to be used."""
    nen_tang: NenTangVideo


@dataclass(frozen=True)
class KetQuaNguonOk:
    video: ThongTinVideo
    ok: Literal[True] = True


@dataclass(frozen=True)
class KetQuaNguonLoi:
    loi: str
    thu_lai_duoc: bool
    loi_cau_hinh: bool = False
    """The disease is on the SERVER, not the video (e.g. yt-dlp not installed).

    A TYPED flag and not a string, because ``loi`` carries text generated by a third party (yt-dlp stderr,
    TikWM error body): that must not flow into the sentence the tool returns to the model. The tool reads this
    flag and picks a completely different sentence: saying "the video may be private" while the server lacks a
    binary sends the operator the wrong way exactly when they need the right way most."""
    can_dang_nhap: bool = False
    """Content that DEMANDS LOGIN (Facebook story, closed-group post).

    A separate flag because this is neither a "broken video" nor a "server missing a tool": it is a kind of
    link the bot can NEVER download, and the user needs to know so they do not retry. Measured: Facebook
    returns ``302 -> login.php``."""
    ok: Literal[False] = False


KetQuaNguon = KetQuaNguonOk | KetQuaNguonLoi

CO_MAC_DINH_WIDTH = 576
CO_MAC_DINH_HEIGHT = 1024
CO_MAC_DINH = {"width": CO_MAC_DINH_WIDTH, "height": CO_MAC_DINH_HEIGHT}
"""Default size when the source does not say.

``sendVideo`` defaults to 1280x720 (LANDSCAPE) if nothing is passed: completely wrong for TikTok/Reels
portrait videos, and Zalo builds the frame from this number so the video shows distorted. The default is
PORTRAIT because that is the overwhelming case of both platforms."""

CO_MAC_DINH_NGANG_WIDTH = 1280
CO_MAC_DINH_NGANG_HEIGHT = 720
CO_MAC_DINH_NGANG = {"width": CO_MAC_DINH_NGANG_WIDTH, "height": CO_MAC_DINH_NGANG_HEIGHT}
"""LANDSCAPE default, used when the source says nothing and the platform is not TikTok.

Equal to the default of zca-js ``sendVideo`` (1280x720). Present because guessing PORTRAIT for a landscape
Facebook video crashed the Zalo app on phones: see ``khung_hinh`` in ``nguon_yt_dlp``."""
