org.gradle.jvmargs=-Xmx6G -XX:MaxMetaspaceSize=1G --enable-native-access=ALL-UNNAMED
kotlin.native.ignoreDisabledTargets=true
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=37

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
