// ported from: src/zalo/zalo-client.ts
// Deviations (forced):
// - credentials are NOT stored on disk: `zalo-credential-store.ts` is deliberately not ported. They arrive
//   in the HTTP body of `start` and live in memory only (zca-js' own context); a QR login hands them to
//   the API as a `credential_updated` event instead of `persistCredentialsFromApi`;
// - the account is not found by `accountId` in a store but logged in from the credential given;
// - `loginWithQRForWeb` takes an AbortSignal and handles two zca-js 2.1.2 facts the original assumed away
//   (see `xuLySuKienQr`): QRCodeExpired does NOT regenerate the QR when a callback is given, and
//   QRCodeDeclined never settles the login promise;
// - `loginWithQR` (QR file on disk, used by `scripts/login-account.ts`) is not ported: no file is written.
import fs from "node:fs";
import { imageSize } from "image-size";
import {
  LoginQRCallbackEventType,
  Zalo,
  type API,
  type Credentials,
  type ImageMetadataGetter,
  type LoginQRCallbackEvent,
} from "zca-js";
import { createLogger } from "./logger.js";
import type { Credential, Gateway, QrLoginEvent, ZaloSession } from "./zalo-types.js";

const log = createLogger("zalo-client");

// zca-js v2 bỏ sharp - phải tự cung cấp hàm đọc metadata ảnh khi gửi ảnh
export const imageMetadataGetter: ImageMetadataGetter = async (filePath) => {
  try {
    const buffer = fs.readFileSync(filePath);
    const { width, height } = imageSize(buffer);
    if (!width || !height) return null;
    return { width, height, size: buffer.byteLength };
  } catch {
    return null;
  }
};

/** The slice of the `Zalo` class used here, so a fake can stand in for it. */
export type ZaloLike = Pick<Zalo, "login" | "loginQR">;

function createZaloInstance(): Zalo {
  return new Zalo({
    checkUpdate: false,
    logging: false,
    selfListen: false,
    imageMetadataGetter,
  });
}

/** Cookie/imei/userAgent of a logged-in API (original `persistCredentialsFromApi`, without the disk write). */
export function exportCredentialFromApi(api: API): Credential {
  const ctx = api.getContext();
  return {
    cookie: ctx.cookie.toJSON()?.cookies ?? [],
    imei: ctx.imei,
    userAgent: ctx.userAgent,
  };
}

function toSession(api: API): ZaloSession {
  return {
    api,
    ownId: api.getOwnId(),
    exportCredential: () => exportCredentialFromApi(api),
  };
}

type QrActions = { abort: () => unknown; retry: () => unknown };

/**
 * Map one zca-js QR event to the event of the web flow.
 *
 * Original comment: QR login for the web dashboard does NOT write a file, it takes the base64 straight
 * from event.data.image (zca-js/src/apis/loginQR.ts: the lib already strips the data:image/png;base64
 * prefix).
 *
 * Two facts verified in zca-js 2.1.2 `dist/apis/loginQR.js` that differ from the original's comments:
 * 1. With a callback, an expired QR (100 s) is NOT regenerated by the library: it only fires
 *    QRCodeExpired with `actions.retry/abort`, and the in-flight wait is aborted. Nobody calling `retry`
 *    makes the login reject. So this function calls `retry()` (or `abort()` when the session is gone).
 * 2. After QRCodeDeclined with a callback the library just `return`s: the promise never settles.
 *    `abort()` settles it (rejects ZaloApiLoginQRAborted); the manager keeps the "declined" status.
 */
function xuLySuKienQr(
  event: LoginQRCallbackEvent,
  onEvent: (event: QrLoginEvent) => void,
  signal: AbortSignal,
  remember: (actions: QrActions | null) => void,
): void {
  const actions = event.actions;
  remember(actions);

  if (event.type === LoginQRCallbackEventType.GotLoginInfo) {
    onEvent({ type: "info" });
    return;
  }
  // The session was superseded or timed out: stop the library from asking Zalo for more QR codes.
  if (signal.aborted) {
    actions?.abort();
    return;
  }
  if (event.type === LoginQRCallbackEventType.QRCodeGenerated) {
    onEvent({ type: "qr", qrBase64: event.data.image });
    return;
  }
  if (event.type === LoginQRCallbackEventType.QRCodeScanned) {
    onEvent({ type: "scanned" });
    return;
  }
  if (event.type === LoginQRCallbackEventType.QRCodeExpired) {
    onEvent({ type: "expired" });
    event.actions.retry();
    return;
  }
  onEvent({ type: "declined" });
  event.actions.abort();
}

export async function loginWithCredentials(
  credential: Credential,
  createZalo: () => ZaloLike = createZaloInstance,
): Promise<ZaloSession> {
  // zca-js validates imei/cookie/userAgent itself; the cast is the type of its own `Credentials`.
  const api = await createZalo().login(credential as Credentials);
  log.info("Đăng nhập bằng credential nhận từ API thành công");
  return toSession(api);
}

export async function loginWithQRForWeb(
  onEvent: (event: QrLoginEvent) => void,
  signal: AbortSignal,
  createZalo: () => ZaloLike = createZaloInstance,
): Promise<ZaloSession> {
  let latestActions: QrActions | null = null;
  const abortLatest = (): void => {
    latestActions?.abort();
  };
  signal.addEventListener("abort", abortLatest, { once: true });
  try {
    const api = await createZalo().loginQR({}, (event) =>
      xuLySuKienQr(event, onEvent, signal, (actions) => {
        latestActions = actions;
      }),
    );
    return toSession(api);
  } finally {
    signal.removeEventListener("abort", abortLatest);
  }
}

/** The real zca-js gateway. Only built when the bridge is enabled. */
export function createZcaGateway(createZalo: () => ZaloLike = createZaloInstance): Gateway {
  return {
    login: (credential) => loginWithCredentials(credential, createZalo),
    loginQR: (onEvent, signal) => loginWithQRForWeb(onEvent, signal, createZalo),
  };
}
