window.PemaFinance={html:()=>`<section class="finance-workspace"><header><div><small>ĐIỀU HÀNH • PEMA CLINIC</small><h1>Tài chính & tiền thủ thuật</h1></div><div class="tools"><input type="hidden" id="role"><label>Kỳ báo cáo<input type="month" id="month"></label><button id="reload">Làm mới</button></div></header><nav class="finance-tabs" aria-label="Phân hệ tài chính">${[['overview','Tổng quan'],['work','Tiền thủ thuật'],... (PemaStaff.current().role==='doctor'?[]:[['rates','Chính sách tỷ lệ'],['receipts','Phiếu thu & thông báo']])].map(([id,label])=>`<button data-finance-tab="${id}">${label}</button>`).join('')}</nav><div id="error" role="alert"></div><div id="content" aria-live="polite">Đang tải dữ liệu…</div><div id="status" role="status"></div></section>`,mount(root){
let disposed=false;
const API='http://127.0.0.1:4174';
const $=q=>root.querySelector(q), money=n=>new Intl.NumberFormat('vi-VN').format(n)+' ₫',esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const account=PemaStaff.current(); $('#role').value=(account.role==='doctor'?'doctor:':account.role==='accountant'?'accountant:':'owner:')+(account.doctor||'D0');
const initialPatient=new URLSearchParams(location.search).get('patient');
let tab=initialPatient?'work':'overview',state,sequence=0,busy=false,dirty=false,paymentKey=crypto.randomUUID();
// en-CA differs across engines; derive ISO calendar components explicitly.
const parts=new Intl.DateTimeFormat('en',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit'}).formatToParts(new Date());$('#month').value=parts.find(x=>x.type==='year').value+'-'+parts.find(x=>x.type==='month').value;
const headers=()=>{const [r,d]=$('#role').value.split(':');return {'Content-Type':'application/json','X-Pema-Role':r,'X-Pema-Doctor':d}};
async function api(path,body){const r=await fetch(API+path,{method:body?'POST':'GET',headers:headers(),body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(8000)});const d=await r.json();if(!r.ok)throw Error(d.error);return d}
async function load(render=true){const id=++sequence;try{const next=await api('/state?month='+$('#month').value);if(disposed||id!==sequence)return;state=next;$('#error').textContent='';if(render)draw()}catch(e){if(!disposed&&id===sequence)$('#error').textContent='Chưa kết nối dữ liệu tài chính: '+e.message+'. Chạy python prototype/finance_server.py rồi thử lại.'}}
const name=id=>state.doctors.find(x=>x.id===id)?.name||id;
const statuses={open:'Đang đối soát',closed:'Đã chốt tháng',paid:'Đã chi',pending:'Chờ duyệt',approved:'Đã duyệt',void:'Đã hủy'};
const basis={net:'Giá sau giảm',list:'Giá niêm yết',collected:'Theo thực thu'};
const metric=(label,value,note)=>`<div class="metric"><span>${label}</span><strong>${money(value)}</strong><small>${note}</small></div>`;
function table(rows){return `<div class="scroll"><table><thead><tr><th>Ngày / Hồ sơ</th><th>Thủ thuật / Bác sĩ</th><th>Doanh số phân bổ</th><th>Cơ sở × tỷ lệ</th><th>Tiền thủ thuật</th><th>Trạng thái</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.date)}<br><span class="muted">${esc(r.patient)}</span></td><td>${esc(r.service)}<br><span class="muted">${esc(name(r.doctor))}</span></td><td>${money(r.revenue)}</td><td>${money(r.base)} × ${r.rate/100}%<br><span class="muted">${basis[r.basis]}</span></td><td><strong>${money(r.fee)}</strong></td><td><span class="badge">${statuses[r.status]}</span>${state.role!=='doctor'&&state.period.status==='open'&&r.status!=='void'?` ${r.status==='pending'?`<button data-command="approve" data-id="${esc(r.id)}">Duyệt</button>`:''} <button data-command="void" data-id="${esc(r.id)}">Hủy</button>`:''}</td></tr>`).join('')||'<tr><td colspan="6">Chưa có lượt thủ thuật trong kỳ này.</td></tr>'}</tbody></table></div>`}
function overview(){const s=state.summary;const mine=state.role==='doctor';return `<section class="hero"><div><small style="color:#b8def5">${mine?'GÓC NHÌN CÁ NHÂN':state.role==='accountant'?'KẾ TOÁN • ĐỐI SOÁT':'BS. TÂM • TỔNG QUAN ĐIỀU HÀNH'}</small><h2>${mine?'Công việc được ghi nhận, thu nhập rõ ràng':'Một màn hình, nắm rõ dòng tiền'}</h2><p>Kỳ ${esc(state.month)} · Doanh số thực hiện và tiền đã thu được theo dõi riêng.</p></div><span class="badge">${statuses[state.period.status]}</span></section><div class="grid">${metric(mine?'Doanh số của tôi':'Doanh số thực hiện',s.revenue,'Theo ngày hoàn tất thủ thuật')}${!mine?metric('Thực thu trong tháng',s.collected,'Theo ngày phiếu thu')+metric('Công nợ hiện tại',s.debt,'Tất cả hóa đơn, không chỉ trong tháng'):metric('Tiền chờ duyệt',s.pending,'Chưa tính vào khoản đã duyệt')}${metric('Tiền thủ thuật đã duyệt',s.fee,'Không phải lợi nhuận phòng khám')}</div><div class="columns"><section class="panel"><h2>${mine?'Chi tiết của tôi':'Đóng góp của đội ngũ'}</h2>${state.doctors.map(d=>{const rows=state.rows.filter(r=>r.doctor===d.id&&r.status!=='void'),rev=rows.reduce((a,r)=>a+r.revenue,0),fee=rows.filter(r=>r.status==='approved').reduce((a,r)=>a+r.fee,0);return `<div class="row"><div><strong>${esc(d.name)}</strong><div class="muted">${rows.length} lượt · Tiền thủ thuật ${money(fee)}</div><div class="bar"><i style="width:${Math.min(100,rev/Math.max(s.revenue,1)*100)}%"></i></div></div><strong>${money(rev)}</strong></div>`}).join('')}</section><section class="panel"><h2>Việc cần đối soát</h2><div class="row"><span>Lượt chờ kế toán duyệt</span><strong>${new Set(state.rows.filter(r=>r.status==='pending').map(r=>r.id)).size}</strong></div><div class="row"><span>Tiền chờ duyệt</span><strong>${money(s.pending)}</strong></div><p class="muted">Tỷ lệ lưu theo từng lượt. Đổi chính sách không tính lại lịch sử. Khoản theo thực thu được đóng băng khi chốt kỳ.</p><button data-finance-tab="work">Mở bảng tiền thủ thuật →</button></section></div>`}
function entryForm(){return `<details class="panel"><summary>+ Ghi nhận lượt thủ thuật đã hoàn tất</summary><form id="entry"><div class="formgrid"><label>Hồ sơ<select name="patient">${Pema.state.patients.filter(p=>/^P\d{3}$/.test(p.id)).map(p=>`<option value="${esc(p.id)}" ${initialPatient===p.id?'selected':''}>${esc(p.name)} · ${esc(p.id)}</option>`).join('')}</select></label><label>Thủ thuật<select name="service">${state.services.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label><label>Ngày thực hiện<input name="date" type="date" value="${state.today}" max="${state.today}" required></label><label>Giá niêm yết<input name="list" type="number" min="1" step="1" value="${state.services[0].price}" required></label><label>Giảm giá<input name="discount" type="number" min="0" step="1" value="0" required></label><label>Gắn hóa đơn đã có<select name="invoice"><option value="">Tạo hóa đơn mới cho lượt này</option>${state.invoices.map(i=>`<option value="${esc(i.id)}">${esc(i.patient)} · ${esc(i.id)} · ${money(i.amount)}</option>`).join('')}</select></label><label>Ghi chú hoàn tất<input name="note" required placeholder="Đã thực hiện, chờ đối soát"></label></div><h3>Ai thực hiện và được ghi nhận?</h3><p class="muted">Tổng tỷ trọng doanh số 100%. Tỷ lệ tiền của mỗi người tính trực tiếp trên cơ sở chính sách; tổng không quá 100%.</p>${[0,1].map(i=>`<div class="person"><label>${i?'Người phối hợp (tùy chọn)':'Bác sĩ chính'}<select name="doctor${i}">${i?'<option value="">Không có</option>':''}${state.doctors.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('')}</select></label><label>Tỷ trọng doanh số %<input name="share${i}" type="number" min="0" max="100" step="0.01" value="${i?0:100}"></label><label>Tỷ lệ tiền thủ thuật %<input name="rate${i}" type="number" min="0" max="100" step="0.01" value="${i?0:state.services[0].rate/100}"></label></div>`).join('')}<button class="primary" type="submit">Ghi nhận • Chờ duyệt</button></form></details>`}
function work(){return `${state.role!=='doctor'&&state.period.status==='open'?entryForm():''}<section class="panel"><div class="row"><div><h2>Bảng tiền thủ thuật • ${esc(state.month)}</h2><span class="badge">${statuses[state.period.status]}</span></div><button id="export">Xuất CSV cho Excel</button></div>${table(state.rows)}${state.role!=='doctor'?`<div class="actions">${state.period.status==='open'?'<button class="primary" data-command="close">Chốt tháng đã kết thúc</button>':state.period.status==='closed'?'<button class="primary" data-command="paid">Xác nhận đã chi</button>':''}</div>`:''}</section>`}
function rates(){return state.role==='doctor'?'<div class="panel">Bác sĩ xem tỷ lệ trên các lượt của mình; chính sách chung thuộc kế toán.</div>':`<div class="panel"><h2>Chính sách theo thủ thuật</h2><p class="muted">Áp dụng cho lượt tạo sau khi lưu. Người phối hợp có thể được kế toán phân bổ riêng tại lượt thực hiện.</p>${state.services.map(s=>`<form class="rate row" data-service="${s.id}"><div><strong>${esc(s.name)}</strong><p class="muted">Phiên bản ${s.version}</p></div><div class="tools"><label>Cơ sở<select name="basis">${Object.entries(basis).map(([k,v])=>`<option value="${k}" ${s.basis===k?'selected':''}>${v}</option>`).join('')}</select></label><label>Tỷ lệ %<input name="rate" type="number" min="0" max="100" step="0.01" value="${s.rate/100}" required></label><button>Lưu tỷ lệ</button></div></form>`).join('')}</div>`}
function receipts(){if(state.role==='doctor')return '<div class="panel">Tài khoản bác sĩ không xem thu tiền toàn phòng khám.</div>';const due=state.invoices.filter(i=>i.source==='finance'&&i.received<i.amount);return `<div class="columns"><section class="panel"><h2>Thu tiền khách hàng</h2><form id="payment"><label>Hóa đơn còn nợ<select name="invoice">${due.map(i=>`<option value="${esc(i.id)}">${esc(i.patient)} · ${money(i.amount-i.received)} · ${esc(i.id.slice(0,18))}</option>`).join('')}</select></label><div class="formgrid" style="margin-top:12px"><label>Số thu<input name="amount" type="number" min="1" step="1" value="${due[0]?due[0].amount-due[0].received:0}" required></label><label>Phương thức<select name="method"><option>Tiền mặt</option><option>Chuyển khoản</option></select></label></div><div class="actions"><button class="primary" ${due.length?'':'disabled'}>Xác nhận thu</button></div></form><p class="muted">Phiếu thu mới đồng bộ với app khi đang mở. Hóa đơn web cũ thu tại Thu ngân Clinic; không thu lại ở đây.</p><h3>Giao dịch trong kỳ</h3>${state.payments.slice(-20).reverse().map(p=>`<div class="row"><div>${esc(p.patient)}<div class="muted">${esc(p.date)} · ${esc(p.method)}</div></div><strong>${money(p.amount)}</strong></div>`).join('')||'<p>Chưa có phiếu thu.</p>'}</section><section class="panel"><h2>Thông báo của chủ phòng khám</h2>${state.role!=='owner'?'<p>Kế toán không đọc inbox của chủ.</p>':state.notifications.map(n=>`<div class="row"><div><strong>${esc(n.title)}</strong><p>${esc(n.body)}</p><small>${esc(n.at.slice(0,16).replace('T',' '))}</small></div>${n.read?'<span class="muted">Đã đọc</span>':`<button data-command="read" data-id="${esc(n.id)}">Đã đọc</button>`}</div>`).join('')||'<p>Thanh toán thành công sẽ xuất hiện tại đây và trên app BS. Tâm.</p>'}</section></div>`}
function draw(){root.querySelectorAll('[data-finance-tab]').forEach(b=>b.classList.toggle('active',b.dataset.financeTab===tab));$('#content').innerHTML=({overview,work,rates,receipts}[tab])();bind()}
async function command(action,data){if(busy)return;busy=true;try{await api('/command/'+action,data);dirty=false;$('#status').textContent='Đã ghi nhận thành công';setTimeout(()=>{if(!disposed)$('#status').textContent=''},2500);await load();return true}catch(e){$('#error').textContent=e.message;return false}finally{busy=false}}
function bind(){root.querySelectorAll('form input, form select').forEach(el=>el.addEventListener('input',()=>dirty=true));root.querySelectorAll('[data-finance-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.financeTab;draw()});root.querySelectorAll('[data-command]').forEach(b=>b.onclick=async()=>{const a=b.dataset.command;const data={id:b.dataset.id,month:state.month};if(a==='void'){data.reason=prompt('Lý do hủy lượt chưa thu tiền');if(!data.reason)return}if(a==='close'&&!confirm('Chốt số liệu tháng '+state.month+'? Các lượt trong kỳ sẽ bị khóa.'))return;if(a==='paid'){data.reference=prompt('Mã chứng từ chi');if(!data.reference)return}await command(a,data)});
const f=$('#entry');if(f){f.elements.service.onchange=()=>{const s=state.services.find(x=>x.id===f.elements.service.value);f.elements.list.value=s.price;f.elements.rate0.value=s.rate/100};f.onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(f));const people=[0,1].filter(i=>v['doctor'+i]).map(i=>({doctor:v['doctor'+i],share:Math.round(Number(v['share'+i])*100),rate:Math.round(Number(v['rate'+i])*100)}));await command('entry',{patient:v.patient,invoice:v.invoice,service:v.service,date:v.date,list:Number(v.list),discount:Number(v.discount),note:v.note,people})}};
root.querySelectorAll('form.rate').forEach(f=>f.onsubmit=async e=>{e.preventDefault();await command('rate',{service:f.dataset.service,basis:f.elements.basis.value,rate:Math.round(Number(f.elements.rate.value)*100)})});
const p=$('#payment');if(p){p.elements.invoice.onchange=()=>{const i=state.invoices.find(i=>i.id===p.elements.invoice.value);p.elements.amount.value=i.amount-i.received;paymentKey=crypto.randomUUID()};p.onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(p));if(await command('payment',{...v,amount:Number(v.amount),id:paymentKey}))paymentKey=crypto.randomUUID()}};
const ex=$('#export');if(ex)ex.onclick=async()=>{try{const r=await fetch(API+'/export?month='+state.month,{headers:headers()});if(!r.ok)throw Error('Không xuất được bảng');const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='Pema-tien-thu-thuat-'+state.month+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){$('#error').textContent=e.message}}}
$('#role').onchange=()=>{dirty=false;state=null;$('#content').textContent='Đang chuyển không gian…';paymentKey=crypto.randomUUID();load()};$('#month').onchange=()=>load();$('#reload').onclick=()=>{dirty=false;load()};load();const timer=setInterval(()=>{if(!document.hidden&&!busy&&!root.querySelector('input:focus,select:focus')&& !$('#entry')?.closest('details')?.open)load(!dirty)},10000);

return ()=>{disposed=true;sequence++;clearInterval(timer)};
}};
