#!/usr/bin/env node
// W2: generates the per-screen specs of the old Pema web into design-specs/web/ (INDEX.md, index.json, screens/<ID>.md)
// from inventory.json (W0), snapshot.json (web-snapshot.cjs) and notes.json (hand-written).
//
//   node web-specs.cjs                 regenerate
//   node web-specs.cjs --check         exit 1 when any generated file is stale, a spec is missing or empty, or the
//                                      Layout of an id misses a field, action, status, filter or notice of its snapshot
//   node web-specs.cjs --show=WB1      print one spec
//   node web-specs.cjs --coverage      print the coverage table (items per id, missing items) and exit 0
//   node web-specs.cjs --check --group=WC   check only the specs of one group (a W3b agent's own ids): freshness and coverage;
//                                      INDEX.md, index.json and BLOCKS.md (which depend on every group) are left to the director
//
// Pure file work: needs no browser and no running web. Line endings of the committed files may be CRLF on a Windows
// checkout; the content is what counts.
const fs = require('fs');
const path = require('path');
const lib = require('./web-specs-lib.cjs');

const args = process.argv.slice(2);
const CHECK = args.includes('--check');
const COVERAGE = args.includes('--coverage');
const SHOW = (args.find((a) => a.startsWith('--show=')) || '').slice(7);
const GROUP = (args.find((a) => a.startsWith('--group=')) || '').slice(8);

const model = lib.loadModel();
const allIds = model.inventory.screens.map((s) => s.id);
// --group=XX: only that group is read, so a group can be checked before the snapshots of the other groups are merged
const ids = GROUP ? allIds.filter((id) => id.startsWith(GROUP)) : allIds;
if (GROUP) model.inventory.screens = model.inventory.screens.filter((s) => ids.includes(s.id));

if (SHOW) {
  const entry = model.inventory.screens.find((s) => s.id.toLowerCase() === SHOW.toLowerCase());
  if (!entry) {
    console.error('No screen ' + SHOW);
    process.exit(1);
  }
  process.stdout.write(lib.specMarkdown(entry, model));
  process.exit(0);
}

const problems = [];
const snapIds = Object.keys(model.snapshot.screens);
// a Next.js-only id (source "nextjs") may have no snapshot: its spec comes from the inventory brief and notes.json
const nextIds = new Set(model.inventory.screens.filter(lib.isNextjs).map((s) => s.id));
for (const id of ids) if (!snapIds.includes(id) && !nextIds.has(id)) problems.push(`${id}: not in snapshot.json (run web-snapshot.cjs)`);
for (const id of snapIds) if (!allIds.includes(id)) problems.push(`${id}: in snapshot.json but not in inventory.json`);
if (model.snapshot.meta.inventory_sha !== lib.inventorySha()) problems.push('snapshot.json was made from another inventory.json (run web-snapshot.cjs)');
if (problems.length) {
  problems.forEach((p) => console.error('FAILED ' + p));
  process.exit(1);
}

const missingAll = lib.coverageAll(model);
const inScope = (id) => !GROUP || id.startsWith(GROUP);
const missing = Object.fromEntries(Object.entries(missingAll).filter(([id]) => inScope(id)));
if (COVERAGE) {
  for (const id of ids) {
    const e = model.snapshot.screens[id];
    const m = missing[id] || [];
    if (!e) {
      const qt = lib.quotedTexts(model.inventory.screens.find((s) => s.id === id));
      console.log(`${id}\tno snapshot (Next.js brief)\tquoted texts: in source ${qt.in_source.length}\tin the front end ${qt.elsewhere.length}\tnot found ${qt.not_found.length}`);
      continue;
    }
    console.log(`${id}\tactions ${e.actions.length}\tfields ${e.fields.length}\tchips/tabs ${e.chips_tabs.length}\tstatuses ${e.badges_status.length}\tkpis ${e.kpis.length}\tnotices ${e.notices.length}\tmissing ${m.length}`);
  }
  process.exit(0);
}

const files = lib.buildFiles(model);
const stale = fs.existsSync(lib.SCREENS) ? fs.readdirSync(lib.SCREENS).filter((f) => f.endsWith('.md') && !files.has(path.join(lib.SCREENS, f))) : [];

// structural checks of every spec
for (const [p, text] of files) {
  if (!p.endsWith('.md') || !p.includes(`${path.sep}screens${path.sep}`)) continue;
  const id = path.basename(p, '.md');
  if (!inScope(id)) continue;
  const layout = /## Layout[^\n]*\n[\s\S]*?```tsx\n([\s\S]*?)\n```/.exec(text);
  if (!layout || layout[1].trim().split('\n').length < 1 || !layout[1].trim()) problems.push(`${id}: empty Layout section`);
  if (/\bTODO\b/.test(text.split('## Layout')[0])) problems.push(`${id}: TODO in the header`);
  if (!text.startsWith('<!-- Generated by')) problems.push(`${id}: no generated header`);
}
// Next.js-only ids: notes.json must say what the screen is for, who may open it and which actions it has
for (const s of model.inventory.screens.filter(lib.isNextjs)) {
  if (!inScope(s.id)) continue;
  const r = (model.notes.routes || {})[s.next_route] || {};
  const own = (model.notes.screens || {})[s.id] || {};
  if (!r.purpose && !own.purpose) problems.push(`${s.id}: notes.json has no purpose for route ${s.next_route}`);
  if (s.kind === 'page' && (!r.gate || !r.roles || !(r.actions || []).length)) problems.push(`${s.id}: notes.json routes.${s.next_route} needs gate, roles and actions`);
  if (s.app_canvas.length) problems.push(`${s.id}: a Next.js-only id must have no app_canvas`);
}
if (!GROUP && files.size - 3 !== ids.length) problems.push(`spec count ${files.size - 2} != inventory count ${ids.length}`);
for (const [id, items] of Object.entries(missing)) {
  problems.push(`${id}: ${items.length} item(s) of the snapshot missing from the Layout: ${items.slice(0, 6).map((i) => `${i.kind} ${JSON.stringify(i.text).slice(0, 60)}`).join('; ')}${items.length > 6 ? ' …' : ''}`);
}

if (CHECK) {
  const changed = [...files].filter(([p]) => !GROUP || inScope(path.basename(p, '.md'))).filter(([p, text]) => !fs.existsSync(p) || lib.lf(fs.readFileSync(p, 'utf8')) !== text).map(([p]) => lib.rel(p));
  if (GROUP) stale.length = 0;
  if (changed.length || stale.length) {
    problems.push(`web specs out of date (${changed.length + stale.length} file(s)): ${[...changed, ...stale].slice(0, 8).join(', ')} … → run node web-specs.cjs`);
  }
  if (problems.length) {
    problems.forEach((p) => console.error('FAILED ' + p));
    process.exit(1);
  }
  console.log(GROUP ? `web specs of ${GROUP} up to date: ${ids.filter(inScope).length} specs, coverage 0 missing` : `web specs up to date: ${ids.length} specs = ${ids.length} inventory ids, coverage 0 missing`);
  process.exit(0);
}

fs.mkdirSync(lib.SCREENS, { recursive: true });
let written = 0;
for (const [p, text] of files) {
  if (fs.existsSync(p) && lib.lf(fs.readFileSync(p, 'utf8')) === text) continue;
  fs.writeFileSync(p, text);
  written++;
}
for (const f of stale) fs.unlinkSync(path.join(lib.SCREENS, f));
const miss = Object.keys(missing).length;
console.log(`web specs: ${ids.length} screens, ${written} file(s) updated -> ${lib.rel(lib.WEB)}; coverage: ${miss} id(s) with missing items`);
if (problems.length) {
  problems.forEach((p) => console.error('WARN ' + p));
}
