#!/usr/bin/env node
// W2: generates the per-screen specs of the old Pema web into design-specs/web/ (INDEX.md, index.json, screens/<ID>.md)
// from inventory.json (W0), snapshot.json (web-snapshot.cjs) and notes.json (hand-written).
//
//   node web-specs.cjs                 regenerate
//   node web-specs.cjs --check         exit 1 when any generated file is stale, a spec is missing or empty, or the
//                                      Layout of an id misses a field, action, status, filter or notice of its snapshot
//   node web-specs.cjs --show=WB1      print one spec
//   node web-specs.cjs --coverage      print the coverage table (items per id, missing items) and exit 0
//
// Pure file work: needs no browser and no running web. Line endings of the committed files may be CRLF on a Windows
// checkout; the content is what counts.
const fs = require('fs');
const path = require('path');
const lib = require('./web-specs-lib.cjs');

const args = process.argv.slice(2);
const CHECK = args.includes('--check');
const COVERAGE = args.includes('--coverage');
const SHOW = (args.find((a) => a.startsWith('--show=')) || '').slice(7);

const model = lib.loadModel();
const ids = model.inventory.screens.map((s) => s.id);

if (SHOW) {
  const entry = model.inventory.screens.find((s) => s.id.toLowerCase() === SHOW.toLowerCase());
  if (!entry) {
    console.error('No screen ' + SHOW);
    process.exit(1);
  }
  process.stdout.write(lib.specMarkdown(entry, model));
  process.exit(0);
}

const problems = [];
const snapIds = Object.keys(model.snapshot.screens);
for (const id of ids) if (!snapIds.includes(id)) problems.push(`${id}: not in snapshot.json (run web-snapshot.cjs)`);
for (const id of snapIds) if (!ids.includes(id)) problems.push(`${id}: in snapshot.json but not in inventory.json`);
if (problems.length) {
  problems.forEach((p) => console.error('FAILED ' + p));
  process.exit(1);
}

const missing = lib.coverageAll(model);
if (COVERAGE) {
  for (const id of ids) {
    const e = model.snapshot.screens[id];
    const m = missing[id] || [];
    console.log(`${id}\tactions ${e.actions.length}\tfields ${e.fields.length}\tchips/tabs ${e.chips_tabs.length}\tstatuses ${e.badges_status.length}\tkpis ${e.kpis.length}\tnotices ${e.notices.length}\tmissing ${m.length}`);
  }
  process.exit(0);
}

const files = lib.buildFiles(model);
const stale = fs.existsSync(lib.SCREENS) ? fs.readdirSync(lib.SCREENS).filter((f) => f.endsWith('.md') && !files.has(path.join(lib.SCREENS, f))) : [];

// structural checks of every spec
for (const [p, text] of files) {
  if (!p.endsWith('.md') || !p.includes(`${path.sep}screens${path.sep}`)) continue;
  const id = path.basename(p, '.md');
  const layout = /## Layout[^\n]*\n[\s\S]*?```tsx\n([\s\S]*?)\n```/.exec(text);
  if (!layout || layout[1].trim().split('\n').length < 1 || !layout[1].trim()) problems.push(`${id}: empty Layout section`);
  if (/\bTODO\b/.test(text.split('## Layout')[0])) problems.push(`${id}: TODO in the header`);
  if (!text.startsWith('<!-- Generated by')) problems.push(`${id}: no generated header`);
}
if (files.size - 2 !== ids.length) problems.push(`spec count ${files.size - 2} != inventory count ${ids.length}`);
for (const [id, items] of Object.entries(missing)) {
  problems.push(`${id}: ${items.length} item(s) of the snapshot missing from the Layout: ${items.slice(0, 6).map((i) => `${i.kind} ${JSON.stringify(i.text).slice(0, 60)}`).join('; ')}${items.length > 6 ? ' …' : ''}`);
}

if (CHECK) {
  const changed = [...files].filter(([p, text]) => !fs.existsSync(p) || lib.lf(fs.readFileSync(p, 'utf8')) !== text).map(([p]) => lib.rel(p));
  if (changed.length || stale.length) {
    problems.push(`web specs out of date (${changed.length + stale.length} file(s)): ${[...changed, ...stale].slice(0, 8).join(', ')} … → run node web-specs.cjs`);
  }
  if (problems.length) {
    problems.forEach((p) => console.error('FAILED ' + p));
    process.exit(1);
  }
  console.log(`web specs up to date: ${ids.length} specs = ${ids.length} inventory ids, coverage 0 missing`);
  process.exit(0);
}

fs.mkdirSync(lib.SCREENS, { recursive: true });
let written = 0;
for (const [p, text] of files) {
  if (fs.existsSync(p) && lib.lf(fs.readFileSync(p, 'utf8')) === text) continue;
  fs.writeFileSync(p, text);
  written++;
}
for (const f of stale) fs.unlinkSync(path.join(lib.SCREENS, f));
const miss = Object.keys(missing).length;
console.log(`web specs: ${ids.length} screens, ${written} file(s) updated -> ${lib.rel(lib.WEB)}; coverage: ${miss} id(s) with missing items`);
if (problems.length) {
  problems.forEach((p) => console.error('WARN ' + p));
}
