#!/usr/bin/env node
// Builds the generated files of design-system/ from tokens.json (single source), scripts/roles.cjs, scripts/component-data.cjs
// and design-specs/web/BLOCKS.md:
//   colors_and_type.css · colors.md · typography.md · spacing-radius-elevation.md · components/*.md · components/INDEX.md
//   preview/*.html · _ds_manifest.json
//
//   node design-system/scripts/build.cjs          write the files
//   node design-system/scripts/build.cjs --check  exit 1 when a committed file differs from what the build writes now
//
// Plain Node, no dependencies. The layout (README.md, colors_and_type.css, preview/ cards, _ds_manifest.json) is the one of the
// earlier `_ds` export so a later publish to claude.ai/design needs no restructuring (see README.md "The _ds export").
const fs = require('fs');
const path = require('path');
const roles = require('./roles.cjs');
const { DATA } = require('./component-data.cjs');

const DS = path.resolve(__dirname, '..');
const ROOT = path.resolve(DS, '..');
const BLOCKS_MD = path.join(ROOT, 'design-specs', 'web', 'BLOCKS.md');
const KMP_COLORS = path.join(ROOT, 'pema-kmp', 'core', 'ui', 'src', 'commonMain', 'kotlin', 'com', 'pema', 'clinic', 'core', 'ui', 'theme', 'PemaColors.kt');
const CHECK = process.argv.includes('--check');

const read = (p) => fs.readFileSync(p, 'utf8').replace(/^﻿/, '').replace(/\r\n/g, '\n');
const tokens = JSON.parse(read(path.join(DS, 'tokens.json')));
const GEN = 'Generated by design-system/scripts/build.cjs. Do not edit: change tokens.json, scripts/roles.cjs or scripts/component-data.cjs and run the build.';

// ---------------------------------------------------------------------------------------------------------------------
// colour helpers
// ---------------------------------------------------------------------------------------------------------------------
const lightColor = (name) => tokens.color.light[name];
const darkColor = (name) => tokens.color.dark[name] ?? tokens.color.light[name];
const colorOf = (mode, name) => (mode === 'dark' ? darkColor(name) : lightColor(name));
const isHex = (v) => /^#[0-9a-f]{6}$/.test(v);

function channel(hex, start) {
  const v = parseInt(hex.slice(start, start + 2), 16) / 255;
  return v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4;
}
const luminance = (hex) => 0.2126 * channel(hex, 1) + 0.7152 * channel(hex, 3) + 0.0722 * channel(hex, 5);
function contrast(a, b) {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
}

// ---------------------------------------------------------------------------------------------------------------------
// validate the dictionaries against tokens.json (an undocumented token or a stale entry stops the build)
// ---------------------------------------------------------------------------------------------------------------------
function same(label, have, want) {
  const a = [...have].sort();
  const b = [...want].sort();
  const missing = b.filter((x) => !a.includes(x));
  const extra = a.filter((x) => !b.includes(x));
  if (missing.length || extra.length) throw new Error(`${label}: no role for [${missing.join(', ')}], role without token [${extra.join(', ')}]`);
}
same('color', Object.keys(roles.COLOR), Object.keys(tokens.color.light));
same('text', Object.keys(roles.TEXT), Object.keys(tokens.text));
same('radius', Object.keys(roles.RADIUS), Object.keys(tokens.radius));
same('shadow', Object.keys(roles.SHADOW), Object.keys(tokens.shadow));
same('space', Object.keys(roles.SPACE), Object.keys(tokens.space));
same('layout', Object.keys(roles.LAYOUT), Object.keys(tokens.layout));
same('z', Object.keys(roles.Z), Object.keys(tokens.z));

// ---------------------------------------------------------------------------------------------------------------------
// BLOCKS.md
// ---------------------------------------------------------------------------------------------------------------------
function splitRow(line) {
  const out = [];
  let cur = '';
  let inCode = false;
  for (const ch of line.replace(/^\|/, '')) {
    if (ch === '`') inCode = !inCode;
    if (ch === '|' && !inCode) {
      out.push(cur.trim());
      cur = '';
    } else cur += ch;
  }
  out.push(cur.trim());
  if (out[out.length - 1] === '') out.pop();
  return out;
}

function parseBlocks() {
  return read(BLOCKS_MD)
    .split('\n')
    .filter((l) => /^\| `[A-Za-z0-9]+` \|/.test(l))
    .map((l) => {
      const cells = splitRow(l);
      if (cells.length !== 6) throw new Error(`BLOCKS.md row with ${cells.length} cells: ${l.slice(0, 80)}`);
      const [name, helper, kit, kmp, rules] = cells;
      return { name: name.replace(/`/g, ''), helper, kit, kmp, rules };
    });
}

// Names that exist in KMP outside core:ui widgets (Compose primitives, a feature screen) or are planned: shown as such in the mapping.
const KMP_OUTSIDE = {
  Spacer: 'Compose primitive',
  Column: 'Compose primitive',
  Row: 'Compose primitive',
  A5PrintPreviewScreen: 'feature:orders screen',
  PemaDropdownField: 'name only (not in core:ui yet)',
};

function kmpNames() {
  const dir = path.dirname(path.dirname(KMP_COLORS));
  const found = new Set();
  const walk = (d) => {
    for (const e of fs.readdirSync(d, { withFileTypes: true })) {
      const p = path.join(d, e.name);
      if (e.isDirectory()) walk(p);
      else if (e.name.endsWith('.kt')) for (const m of read(p).matchAll(/\b(?:fun|object|class)\s+([A-Z][A-Za-z0-9]+)/g)) found.add(m[1]);
    }
  };
  walk(dir);
  return found;
}

function kitStatus(kit) {
  if (/^kit gap/.test(kit)) return 'kit gap';
  if (/^web-only/.test(kit)) return 'kit gap (web-only)';
  if (/^none/.test(kit)) return 'none';
  if (/shared/.test(kit)) return 'shared (next to the kit)';
  return 'src/ui';
}

function kmpStatus(kmp, names) {
  const list = [...kmp.matchAll(/`([A-Za-z0-9]+)`/g)].map((m) => m[1]);
  if (!list.length) return { text: /^none/.test(kmp) ? 'none' : kmp, names: [] };
  return {
    text: list.map((n) => (names.has(n) ? `\`${n}\` (core:ui)` : `\`${n}\` (${KMP_OUTSIDE[n] || 'name only'})`)).join(', '),
    names: list,
  };
}

// ---------------------------------------------------------------------------------------------------------------------
// colors_and_type.css
// ---------------------------------------------------------------------------------------------------------------------
function buildCss() {
  const L = [];
  L.push(`/* Pema design system: foundations. ${GEN} */`);
  L.push('/* Same names as pema-agent/frontend/src/ui/tokens.css: --color-*, --radius-*, --shadow-*, --text-*, --space-*, --layout-*, --z-*, --font-family-ui. */');
  L.push(':root {');
  for (const [k, v] of Object.entries(tokens.color.light)) L.push(`  --color-${k}: ${v};`);
  for (const group of ['radius', 'shadow', 'text', 'space', 'layout', 'z']) for (const [k, v] of Object.entries(tokens[group])) L.push(`  --${group}-${k}: ${v};`);
  L.push(`  --breakpoint-wide: ${tokens.breakpoint.wide};`);
  L.push(`  --font-family-ui: ${tokens.font['family-ui']};`);
  L.push('}');
  L.push('');
  L.push('/* Dark mode redefines colours only. Put the class on the root element of the page or frame. */');
  L.push('.dark, [data-theme="dark"] {');
  for (const [k, v] of Object.entries(tokens.color.dark)) L.push(`  --color-${k}: ${v};`);
  L.push('}');
  L.push('');
  L.push('body { font-family: var(--font-family-ui), system-ui, sans-serif; font-size: var(--text-body); line-height: 1.5; color: var(--color-ink); background: var(--color-canvas); }');
  return L.join('\n') + '\n';
}

// ---------------------------------------------------------------------------------------------------------------------
// colors.md
// ---------------------------------------------------------------------------------------------------------------------
const CONTRAST_PAIRS = [
  ['ink', 'surface', 'Body text on a card'],
  ['ink', 'canvas', 'Body text on the page'],
  ['ink-soft', 'surface', 'Metadata on a card'],
  ['ink-soft', 'canvas', 'Metadata on the page'],
  ['ink-soft', 'tile', 'Metadata on a tile or neutral badge'],
  ['heading', 'surface', 'Titles and KPI values'],
  ['link', 'surface', 'Links and selected tab'],
  ['surface', 'brand-500', 'Primary button label'],
  ['surface', 'brand-600', 'Primary hover, toast, hero start'],
  ['brand-700', 'brand-50', 'Brand badge, selected menu item'],
  ['surface', 'accent-strong', 'Sidebar count badge'],
  ['success', 'success-soft', 'Success badge or notice'],
  ['info', 'info-soft', 'Info badge or notice'],
  ['warning', 'warning-soft', 'Warning badge or notice'],
  ['danger', 'danger-soft', 'Danger badge or notice'],
  ['surface', 'danger', 'Solid danger button label'],
];

function kmpColors() {
  const map = {};
  for (const m of read(KMP_COLORS).matchAll(/val\s+([A-Za-z0-9]+)\s*=\s*Color\(0xFF([0-9A-Fa-f]{6})\)/g)) map[m[1]] = '#' + m[2].toLowerCase();
  return map;
}
const KMP_OF = {
  'brand-500': 'Blue',
  'brand-600': 'Navy',
  'brand-400': 'Sky',
  ink: 'Ink',
  'ink-soft': 'Muted',
  canvas: 'Paper',
  line: 'Line',
  'line-strong': 'FieldBorder',
  'brand-50': 'Tint',
  surface: 'White',
  danger: 'Error',
};

function buildColors() {
  const swatch = (hex) => `\`${hex}\``;
  const L = [];
  L.push(`<!-- ${GEN} -->`);
  L.push('# Colour roles');
  L.push('');
  L.push('Source: `tokens.json` (`color.light`, `color.dark`). A colour is always used by its **name** (CSS variable `--color-<name>`), never by hex. The canvases are drawn with these variables only; `scripts/check.cjs` fails when a frame uses a colour that is not listed here.');
  L.push('');
  L.push('## Identity');
  L.push('');
  L.push('| Role | Token | Light | Dark |');
  L.push('|---|---|---|---|');
  const identity = [
    ['Primary', 'brand-500'],
    ['Navy', 'brand-600'],
    ['Sky', 'brand-400'],
    ['Ink', 'ink'],
    ['Ink soft (muted)', 'ink-soft'],
    ['Canvas (paper)', 'canvas'],
    ['Surface', 'surface'],
    ['Line', 'line'],
    ['Tile', 'tile'],
    ['Success', 'success'],
    ['Info', 'info'],
    ['Warning', 'warning'],
    ['Danger', 'danger'],
  ];
  for (const [role, name] of identity) L.push(`| ${role} | \`${name}\` | ${swatch(lightColor(name))} | ${swatch(darkColor(name))} |`);
  L.push('');
  L.push('Hierarchy: light canvas, white surface, ink text, one prominent action. Sky is decoration; status colours always come with a word.');
  L.push('');
  const groups = [...new Set(Object.values(roles.COLOR).map((r) => r[0]))];
  for (const g of groups) {
    L.push(`## ${g}`);
    L.push('');
    L.push('| Token | CSS variable | Light | Dark | Role | Used for |');
    L.push('|---|---|---|---|---|---|');
    for (const [name, [group, role, use]] of Object.entries(roles.COLOR)) {
      if (group !== g) continue;
      const dark = tokens.color.dark[name];
      L.push(`| \`${name}\` | \`--color-${name}\` | ${swatch(lightColor(name))} | ${dark ? swatch(dark) : 'same'} | ${role} | ${use} |`);
    }
    L.push('');
  }
  L.push('Status colours come in triples: `<tone>` is text and icon, `<tone>-soft` the background, `<tone>-line` the border. Tones: success, info, warning, danger.');
  L.push('');
  L.push('## Contrast (WCAG 2.1 ratio of the text pairs, computed from tokens.json)');
  L.push('');
  L.push('Target 4.5:1 for normal text.');
  L.push('');
  L.push('| Pair | Use | Light | Dark |');
  L.push('|---|---|---|---|');
  for (const [fg, bg, use] of CONTRAST_PAIRS) {
    const cell = (mode) => {
      const r = contrast(colorOf(mode, fg), colorOf(mode, bg));
      return `${r.toFixed(2)}:1${r >= 4.5 ? '' : ' (below 4.5)'}`;
    };
    L.push(`| \`${fg}\` on \`${bg}\` | ${use} | ${cell('light')} | ${cell('dark')} |`);
  }
  L.push('');
  L.push('## Web token and the app counterpart (KMP `PemaColors`)');
  L.push('');
  L.push('The app (`pema-kmp/core/ui`, `PemaColors.kt`) predates the token set. Where a counterpart exists, the table shows whether the value is the same today. Tokens without a row have no `PemaColors` entry yet; the KMP step reads them from `tokens.json`.');
  L.push('');
  L.push('| Token | Web (light) | `PemaColors` | App value | Same |');
  L.push('|---|---|---|---|---|');
  const kmp = kmpColors();
  for (const [name, k] of Object.entries(KMP_OF)) {
    const v = kmp[k];
    L.push(`| \`${name}\` | ${swatch(lightColor(name))} | \`${k}\` | ${v ? swatch(v) : 'not found'} | ${v === lightColor(name) ? 'yes' : 'no'} |`);
  }
  L.push('');
  return L.join('\n');
}

// ---------------------------------------------------------------------------------------------------------------------
// typography.md
// ---------------------------------------------------------------------------------------------------------------------
function buildTypography() {
  const L = [];
  L.push(`<!-- ${GEN} -->`);
  L.push('# Typography');
  L.push('');
  L.push(`Font: **${tokens.font['family-ui'].replace(/"/g, '')}** (variable \`--font-family-ui\`, fallback \`system-ui, sans-serif\`). Weights 400, 500, 600, 700. Local files and the OFL licence are in \`prototype/shared/assets/\` (\`be-vietnam-pro-*.ttf\`); the app bundles them in \`pema-kmp/core/ui\`; the Next.js front end loads the family through \`next/font\`. Vietnamese needs this font: never fall back to a serif in inputs or headings. Code and raw text use the system monospace (\`ui-monospace, Menlo, Consolas\`) at label size.`);
  L.push('');
  L.push('## Scale');
  L.push('');
  L.push('Source: `tokens.json` `text` (px; dp/sp in the app). Always use the token name (`--text-<name>`), never a pixel value.');
  L.push('');
  L.push('| Token | Size | Role | Weight | Line height | Used for |');
  L.push('|---|---|---|---|---|---|');
  for (const [name, px] of Object.entries(tokens.text)) {
    const [role, weight, lh, use] = roles.TEXT[name];
    L.push(`| \`${name}\` | ${px} | ${role} | ${weight} | ${lh} | ${use} |`);
  }
  L.push('');
  L.push('## Headings and titles');
  L.push('');
  L.push('| Element | Token | Weight | Colour |');
  L.push('|---|---|---|---|');
  L.push('| Page title (`pageHead`) | `page` 30 (title 25 at 390) | 700 | `heading` |');
  L.push('| `h1` | `title` 25 | 700 | `heading` |');
  L.push('| `h2` | `subtitle` 20 | 700 | `heading` |');
  L.push('| `h3` | `section` 16 | 700 | `heading` |');
  L.push('| `h4` | `body-lg` 15 | 600 | `ink` |');
  L.push('| Card title (`card`) | `body-lg` 15 | 700 | `heading` (tint colour when tinted) |');
  L.push('| Dialog title | `section` 16 | 600 | `ink` |');
  L.push('| KPI value | `metric` 27 (22 at 390) | 700 | `heading` |');
  L.push('| Eyebrow | `eyebrow` 10 | 600, uppercase, +0.1em | `info` |');
  L.push('');
  L.push('Note: `design-specs/web/BLOCKS.md` says "h3 = card title 16"; the card block draws its title at 15 (`body-lg`), the `h3` heading at 16. Both are as the canvas CSS draws them.');
  L.push('');
  L.push('## Rules');
  L.push('');
  L.push('- Body text 14 or 15; label 12; never shrink text to cram content, wrap or use a card instead. Test long Vietnamese names, prices and multi-line notes.');
  L.push('- Weights above 700 (the old web used 750 and 800 in a few places) are not part of the system.');
  L.push('- A money value never wraps before the currency sign: the sample data uses a no-break space before "₫".');
  L.push('- Text colours: `ink` for content, `ink-soft` for metadata (contrast in colors.md), `link` for links and selected tabs, status text only together with the status word.');
  L.push('- Phone (390): page title 25, KPI value 22; on Patient Mobile frames the hero title is 21; everything else keeps its token.');
  L.push('');
  return L.join('\n');
}

// ---------------------------------------------------------------------------------------------------------------------
// spacing-radius-elevation.md
// ---------------------------------------------------------------------------------------------------------------------
function buildSpacing() {
  const L = [];
  L.push(`<!-- ${GEN} -->`);
  L.push('# Spacing, radius, elevation, layout');
  L.push('');
  L.push('Source: `tokens.json` (`space`, `radius`, `shadow`, `layout`, `z`, `breakpoint`). Values are logical pixels (dp in the app); `shadow` and `breakpoint` are web hints.');
  L.push('');
  L.push('## Spacing scale');
  L.push('');
  L.push('Group by proximity and alignment; do not wrap every label in a card.');
  L.push('');
  L.push('| Token | Value | Used for |');
  L.push('|---|---|---|');
  for (const [name, px] of Object.entries(tokens.space)) L.push(`| \`space-${name}\` | ${px} | ${roles.SPACE[name]} |`);
  L.push('');
  L.push('## Radius');
  L.push('');
  L.push('| Token | Value | Role | Used for |');
  L.push('|---|---|---|---|');
  for (const [name, px] of Object.entries(tokens.radius)) L.push(`| \`radius-${name}\` | ${px} | ${roles.RADIUS[name][0]} | ${roles.RADIUS[name][1]} |`);
  L.push('');
  L.push('The app uses 18 for a card and 14 for controls (`pema-design/references/visual-system.md`); the web does not copy them mechanically.');
  L.push('');
  L.push('## Elevation');
  L.push('');
  L.push('Depth comes from the border and one of two shadows. Never mix recipes on a screen.');
  L.push('');
  L.push('| Token | Value | Role | Used for |');
  L.push('|---|---|---|---|');
  for (const [name, v] of Object.entries(tokens.shadow)) L.push(`| \`shadow-${name}\` | \`${v}\` | ${roles.SHADOW[name][0]} | ${roles.SHADOW[name][1]} |`);
  L.push('');
  L.push('## Layout');
  L.push('');
  L.push('| Token | Value | Used for |');
  L.push('|---|---|---|');
  for (const [name, px] of Object.entries(tokens.layout)) L.push(`| \`layout-${name}\` | ${px} | ${roles.LAYOUT[name]} |`);
  L.push('');
  L.push('## Frame sizes of the canvases');
  L.push('');
  L.push('| Frame | Size | Top bar | Content padding x | Page gap | Card padding |');
  L.push('|---|---|---|---|---|---|');
  L.push(`| Desktop | 1440 x 900 | ${tokens.layout['topbar-h']} | ${tokens.layout['content-pad-x']} | ${tokens.space['4']} | ${tokens.space['5']} |`);
  L.push(`| Wide | 1920 x 1020 | ${tokens.layout['topbar-h-wide']} | ${tokens.layout['content-pad-x']} | ${tokens.space['5']} | ${tokens.space['5']} |`);
  L.push(`| Phone | 390 x 844 | 56px | 16px | ${tokens.space['4']} | ${tokens.space['4']} |`);
  L.push('');
  L.push(`Breakpoint \`wide\` is ${tokens.breakpoint.wide} (1600px): the step the old web used for four-column grids and the taller top bar.`);
  L.push('');
  L.push('## Touch targets');
  L.push('');
  L.push(`Minimum ${tokens.layout['touch-min']}. Buttons and chips are 44px high on a phone and 40px (buttons) or 36px (chips) on a desktop; native app controls keep 48.`);
  L.push('');
  L.push('## Stacking order');
  L.push('');
  L.push('| Token | Value | Used for |');
  L.push('|---|---|---|');
  for (const [name, v] of Object.entries(tokens.z)) L.push(`| \`z-${name}\` | ${v} | ${roles.Z[name]} |`);
  L.push('');
  L.push('## Values the canvas draws off the scale');
  L.push('');
  L.push('Small sizes that have no token. They are fixed by the component, not chosen per screen.');
  L.push('');
  L.push('| Value | Where |');
  L.push('|---|---|');
  L.push('| 4px, 6px, 8px radius | legend swatch, checkbox and id chip, photo tag |');
  L.push('| 6px | badge dot gap and dot size |');
  L.push('| 10px, 14px, 18px | list row and card paddings in dense blocks |');
  L.push('| 56px | time column of the board, phone top bar |');
  L.push('');
  return L.join('\n');
}

// ---------------------------------------------------------------------------------------------------------------------
// components
// ---------------------------------------------------------------------------------------------------------------------
function buildComponent(b, names) {
  const d = DATA[b.name];
  if (!d) throw new Error(`component-data.cjs has no entry for block ${b.name}`);
  const kmp = kmpStatus(b.kmp, names);
  const bullets = (a) => a.map((x) => `- ${x}`).join('\n');
  return [
    `<!-- ${GEN} -->`,
    `# \`${b.name}\``,
    '',
    `Helper: ${b.helper}  `,
    `Kit (\`src/ui\`): ${b.kit} · status: ${kitStatus(b.kit)}  `,
    `App (KMP \`core:ui\`): ${kmp.text}`,
    '',
    '## Anatomy',
    '',
    d.anatomy,
    '',
    '## Variants',
    '',
    bullets(d.variants),
    '',
    '## States',
    '',
    bullets(d.states),
    '',
    '## Tokens',
    '',
    d.tokens,
    '',
    '## Do',
    '',
    bullets(d.dos),
    '',
    "## Don't",
    '',
    bullets(d.donts),
    '',
    '## Web (1440 and 1920)',
    '',
    d.web,
    '',
    '## Mobile (390)',
    '',
    d.mobile,
    '',
    '## Rules (design-specs/web/BLOCKS.md)',
    '',
    b.rules,
    '',
  ].join('\n');
}

function buildComponentIndex(blocks, names) {
  const L = [];
  L.push(`<!-- ${GEN} -->`);
  L.push('# Components: block, page, `src/ui` component, KMP composable');
  L.push('');
  L.push('One page per block of `design-specs/web/BLOCKS.md`. Status words: `src/ui` = a component exists in `pema-agent/frontend/src/ui`; `shared` = exists next to the kit (`ops-ui.tsx`, `components/admin/shared`); `kit gap` = the canvas draws it, the kit has no component yet (names only, U-package work); KMP: `core:ui` = composable exists, otherwise the place or "name only".');
  L.push('');
  L.push('| Block | Page | `src/ui` component | Kit status | KMP `core:ui` composable |');
  L.push('|---|---|---|---|---|');
  for (const b of blocks) L.push(`| \`${b.name}\` | [${b.name}.md](${b.name}.md) | ${b.kit} | ${kitStatus(b.kit)} | ${kmpStatus(b.kmp, names).text} |`);
  L.push('');
  const gaps = blocks.filter((b) => /^kit gap|^web-only/.test(b.kit)).length;
  L.push(`${blocks.length} blocks, ${gaps} without a kit component yet.`);
  L.push('');
  return L.join('\n');
}

// ---------------------------------------------------------------------------------------------------------------------
// preview cards
// ---------------------------------------------------------------------------------------------------------------------
const PAGE = (title, body, extraCss = '') =>
  `<!doctype html>
<html lang="vi">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- ${GEN} -->
<title>${title}</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:wght@400;500;600;700&display=swap">
<link rel="stylesheet" href="../colors_and_type.css">
<style>
body{margin:0;padding:20px;background:var(--color-surface)}
.row{display:flex;flex-wrap:wrap;gap:12px;align-items:flex-start}
.sw{width:88px}.sw i{display:block;height:48px;border-radius:var(--radius-tile);border:1px solid var(--color-line)}
.sw b{display:block;margin-top:6px;font-size:var(--text-label);color:var(--color-ink)}.sw small{font-size:var(--text-micro);color:var(--color-ink-soft)}
.bt{display:inline-flex;align-items:center;min-height:40px;padding:0 14px;border-radius:var(--radius-control);border:1px solid transparent;font:600 var(--text-small) var(--font-family-ui),sans-serif}
.bd{display:inline-flex;align-items:center;gap:6px;border:1px solid var(--color-line);border-radius:var(--radius-pill);padding:2px 10px;font-size:var(--text-label);font-weight:500}
.bd:before{content:"";width:6px;height:6px;border-radius:99px;background:currentColor}
.card{background:var(--color-surface);border:1px solid var(--color-line);border-radius:var(--radius-card);box-shadow:var(--shadow-card);padding:20px}
${extraCss}
</style>
</head>
<body>
${body}
</body>
</html>
`;

const swatchRow = (names) =>
  `<div class="row">${names.map((n) => `<div class="sw"><i style="background:var(--color-${n})"></i><b>${n}</b><small>${lightColor(n)}</small></div>`).join('')}</div>`;

function statusRow(mode) {
  const tones = ['success', 'info', 'warning', 'danger'];
  return `<div class="${mode === 'dark' ? 'dark' : ''}" style="background:var(--color-canvas);padding:12px;border-radius:var(--radius-tile);margin-bottom:10px"><div class="row">${tones
    .map((t) => `<span class="bd" style="background:var(--color-${t}-soft);border-color:var(--color-${t}-line);color:var(--color-${t})">${t}</span>`)
    .join('')}<span class="bd" style="background:var(--color-tile);color:var(--color-ink-soft)">neutral</span><span class="bd" style="background:var(--color-brand-50);border-color:var(--color-brand-100);color:var(--color-brand-700)">brand</span></div></div>`;
}

const CARDS = [
  ['colors-brand', 'Colors', '700x200', 'Primary, navy, sky and the brand wash scale', 'Brand palette', () => PAGE('Brand palette', swatchRow(['brand-50', 'brand-100', 'brand-200', 'brand-400', 'brand-500', 'brand-600', 'brand-700']))],
  ['colors-surface-ink', 'Colors', '700x200', 'Canvas, surface, tile, field, ink, ink-soft, heading, link', 'Surface and ink', () => PAGE('Surface and ink', swatchRow(['canvas', 'canvas-alt', 'surface', 'tile', 'field', 'table-head', 'ink', 'ink-soft', 'heading', 'link']))],
  ['colors-lines', 'Colors', '700x170', 'Line, strong line, focus', 'Lines', () => PAGE('Lines', swatchRow(['line', 'line-strong', 'focus', 'accent', 'accent-strong']))],
  ['colors-status', 'Colors', '700x200', 'Success, info, warning, danger in light and dark', 'Status', () => PAGE('Status', statusRow('light') + statusRow('dark'))],
  [
    'type-scale',
    'Type',
    '700x420',
    'Be Vietnam Pro, eleven sizes from eyebrow 10 to page 30',
    'Type scale',
    () =>
      PAGE(
        'Type scale',
        Object.entries(tokens.text)
          .reverse()
          .map(([n, px]) => `<div style="display:flex;align-items:baseline;gap:16px;margin-bottom:6px"><code style="width:96px;color:var(--color-ink-soft);font-size:var(--text-label)">${n} ${px}</code><span style="font-size:var(--text-${n});color:var(--color-heading);font-weight:${n === 'body' || n === 'small' || n === 'label' || n === 'micro' ? 500 : 700}">Chăm sóc da sau thủ thuật</span></div>`)
          .join(''),
      ),
  ],
  [
    'spacing-scale',
    'Spacing',
    '700x230',
    'Space tokens 4 to 24',
    'Spacing scale',
    () => PAGE('Spacing scale', Object.entries(tokens.space).map(([n, px]) => `<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px"><code style="width:72px;font-size:var(--text-label);color:var(--color-ink-soft)">space-${n} ${px}</code><i style="display:block;height:12px;width:${px};background:var(--color-brand-500);border-radius:2px"></i></div>`).join('')),
  ],
  [
    'spacing-radii',
    'Spacing',
    '700x200',
    'Radius tokens from field 9 to pill',
    'Radius',
    () => PAGE('Radius', `<div class="row">${Object.entries(tokens.radius).map(([n, px]) => `<div class="sw"><i style="background:var(--color-tile);border-radius:var(--radius-${n});height:64px"></i><b>${n}</b><small>${px}</small></div>`).join('')}</div>`),
  ],
  [
    'spacing-shadows',
    'Spacing',
    '700x230',
    'Card shadow and pop shadow',
    'Elevation',
    () => PAGE('Elevation', `<div class="row" style="gap:32px;padding:16px;background:var(--color-canvas)">${Object.keys(tokens.shadow).map((n) => `<div class="sw" style="width:140px"><i style="background:var(--color-surface);height:72px;box-shadow:var(--shadow-${n})"></i><b>shadow-${n}</b></div>`).join('')}</div>`),
  ],
  [
    'components-buttons',
    'Components',
    '700x180',
    'Primary, secondary, danger, solid danger, quiet',
    'Buttons',
    () =>
      PAGE(
        'Buttons',
        `<div class="row"><span class="bt" style="background:var(--color-brand-500);border-color:var(--color-brand-500);color:var(--color-surface)">Lưu</span><span class="bt" style="background:var(--color-surface);border-color:var(--color-line-strong);color:var(--color-ink)">Hủy</span><span class="bt" style="background:var(--color-surface);border-color:var(--color-danger-line);color:var(--color-danger)">Xóa</span><span class="bt" style="background:var(--color-danger);border-color:var(--color-danger);color:var(--color-surface)">Xóa vĩnh viễn</span><span class="bt" style="padding:0;color:var(--color-link)">Xem chi tiết</span><span class="bt" style="background:var(--color-brand-500);color:var(--color-surface);opacity:.5">Đang tắt</span></div>`,
      ),
  ],
  [
    'components-badges-chips',
    'Components',
    '700x180',
    'Status badges and filter chips',
    'Badges and chips',
    () =>
      PAGE(
        'Badges and chips',
        `${statusRow('light')}<div class="row"><span class="bt" style="min-height:36px;border-radius:var(--radius-pill);background:var(--color-brand-500);color:var(--color-surface);font-weight:500">Tất cả 12</span><span class="bt" style="min-height:36px;border-radius:var(--radius-pill);border-color:var(--color-line);color:var(--color-ink-soft);font-weight:500">Hôm nay 4</span><span class="bt" style="min-height:36px;border-radius:var(--radius-pill);border-color:var(--color-line);color:var(--color-ink-soft);font-weight:500;opacity:.5">Đã hủy</span></div>`,
      ),
  ],
  [
    'components-card-kpi',
    'Components',
    '700x200',
    'Card with title and a KPI tile',
    'Card and KPI',
    () =>
      PAGE(
        'Card and KPI',
        `<div class="row"><div class="card" style="width:260px"><div style="font-size:var(--text-body-lg);font-weight:700;color:var(--color-heading)">Lịch hẹn hôm nay</div><div style="margin-top:2px;font-size:var(--text-label);color:var(--color-ink-soft)">Cập nhật 09:00</div></div><div class="card" style="width:200px;padding:19px 20px"><div style="font-size:var(--text-label);color:var(--color-ink-soft)">Lịch hôm nay</div><div style="margin-top:8px;font-size:var(--text-metric);font-weight:700;color:var(--color-heading)">12</div><div style="margin-top:4px;font-size:var(--text-label);color:var(--color-success)">Tăng so với hôm qua</div></div></div>`,
      ),
  ],
  [
    'components-fields',
    'Components',
    '700x220',
    'Field states: default, error, disabled',
    'Fields',
    () => {
      const field = (label, extra, msg) => `<div style="width:200px"><div style="font-size:var(--text-label);font-weight:600;color:var(--color-ink-soft);margin-bottom:6px">${label}</div><div style="min-height:40px;padding:8px 12px;box-sizing:border-box;border:1px solid var(--color-line-strong);background:var(--color-field);border-radius:var(--radius-field);font-size:var(--text-body-lg);color:var(--color-ink);${extra}">Nguyễn Thu Hà</div>${msg ? `<div style="margin-top:4px;font-size:var(--text-label);color:var(--color-danger)">${msg}</div>` : ''}</div>`;
      return PAGE('Fields', `<div class="row">${field('Họ tên', '')}${field('Họ tên (lỗi)', 'border-color:var(--color-danger)', 'Vui lòng nhập họ tên')}${field('Họ tên (khóa)', 'opacity:.6')}</div>`);
    },
  ],
];

function buildManifest() {
  const tokensList = [];
  for (const [k, v] of Object.entries(tokens.color.light)) tokensList.push({ name: `--color-${k}`, value: v, kind: 'color', definedIn: 'colors_and_type.css' });
  for (const group of ['radius', 'shadow', 'text', 'space', 'layout', 'z']) for (const [k, v] of Object.entries(tokens[group])) tokensList.push({ name: `--${group}-${k}`, value: v, kind: group, definedIn: 'colors_and_type.css' });
  return {
    namespace: 'PemaDesignSystem',
    components: [],
    startingPoints: [],
    cards: CARDS.map(([file, group, viewport, subtitle, name]) => ({ path: `preview/${file}.html`, group, viewport, subtitle, name })),
    templates: [],
    hasThumbnailHtml: false,
    globalCssPaths: ['colors_and_type.css'],
    tokens: tokensList,
    themes: [{ name: 'dark', selector: '.dark, [data-theme="dark"]' }],
    fonts: [],
    brandFonts: [{ family: 'Be Vietnam Pro', status: 'google-fonts-link', tokens: ['--font-family-ui'], path: 'colors_and_type.css' }],
    source: 'repo: design-system/ (tokens.json is the single source; see README.md)',
  };
}

// ---------------------------------------------------------------------------------------------------------------------
// collect, then write or compare
// ---------------------------------------------------------------------------------------------------------------------
function buildAll() {
  const blocks = parseBlocks();
  const names = kmpNames();
  const files = new Map();
  files.set('colors_and_type.css', buildCss());
  files.set('colors.md', buildColors());
  files.set('typography.md', buildTypography());
  files.set('spacing-radius-elevation.md', buildSpacing());
  for (const b of blocks) files.set(`components/${b.name}.md`, buildComponent(b, names));
  files.set('components/INDEX.md', buildComponentIndex(blocks, names));
  for (const [file, , , , , render] of CARDS) files.set(`preview/${file}.html`, render());
  files.set('_ds_manifest.json', JSON.stringify(buildManifest(), null, 2) + '\n');
  return { files, blocks };
}

function main() {
  const { files, blocks } = buildAll();
  const problems = [];
  for (const [rel, text] of files) {
    const target = path.join(DS, rel);
    const have = fs.existsSync(target) ? read(target) : null;
    if (CHECK) {
      if (have !== text) problems.push(`${rel} ${have === null ? 'is missing' : 'is stale'}`);
      continue;
    }
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, text);
  }
  if (CHECK) {
    // a page of a block that no longer exists in BLOCKS.md
    const wanted = new Set(blocks.map((b) => `${b.name}.md`).concat('INDEX.md'));
    for (const f of fs.readdirSync(path.join(DS, 'components'))) if (!wanted.has(f)) problems.push(`components/${f} has no block in BLOCKS.md`);
    if (problems.length) {
      problems.forEach((p) => console.error('FAILED ' + p));
      console.error('run: node design-system/scripts/build.cjs');
      process.exit(1);
    }
    console.log(`generated files up to date: ${files.size} files, ${blocks.length} component pages`);
  } else {
    console.log(`wrote ${files.size} files (${blocks.length} component pages)`);
  }
}

if (require.main === module) main();

module.exports = { parseBlocks, kmpNames, kmpStatus, KMP_OUTSIDE, buildAll, contrast, tokens };
