// Curated content of the component pages, one entry per block of design-specs/web/BLOCKS.md.
// build.cjs joins it with the BLOCKS.md row (helper, kit component, KMP analogue, rules), so those columns are never retyped here.
// Source of every value: Pema Web redesign canvas/template.html (the CSS the frames are drawn with), the src/ui kit and
// .claude/skills/pema-web-design/references/blocks-web.md. Tokens are written by name (colors.md, typography.md, spacing-radius-elevation.md).
// Fields: anatomy (what is drawn, in order), variants, states, tokens, dos, donts, web (1440/1920), mobile (390).

const c = (anatomy, variants, states, tokens, dos, donts, web, mobile) => ({ anatomy, variants, states, tokens, dos, donts, web, mobile });

const SAME = 'Same as 1440; the frame is narrower, nothing is hidden.';
const NONE_STATE = ['Static: it has no hover, focus or disabled state of its own'];

const DATA = {
  h: c(
    'Optional eyebrow, the heading, optional sub line.',
    ['h1 (title 25/700, heading colour)', 'h2 (subtitle 20/700)', 'h3 (section 16/700)', 'h4 (body-lg 15/600, ink)'],
    NONE_STATE,
    'heading, ink, ink-soft (sub line, label 12), info (eyebrow)',
    ['Use the level for hierarchy, not for size', 'Put a sub line under it only when it adds information'],
    ['Do not use h1 for a card title (a card has its own title)', 'Do not set a size or colour in a part'],
    'Block-level text; the page title is `pageHead`, not `h`.',
    SAME,
  ),
  pageHead: c(
    'Title (page 30/700), sub line (body, ink-soft), actions on the right; optional eyebrow.',
    ['With or without actions', 'With an eyebrow'],
    ['Actions follow the button states'],
    'heading, ink-soft, text-page, text-body',
    ['One per page, first block', 'Primary action last, secondary before it'],
    ['Do not repeat the menu name as the only text', 'Do not put filters here (filters are chips or fields under it)'],
    'Title 30; actions sit on the right and wrap under the title when the line is full.',
    'Title drops to 25 (title); actions wrap below the text and become full-height 44px buttons.',
  ),
  hero: c(
    'Gradient band (brand-600 to brand-500), decorative icon at 10% opacity, optional kicker (eyebrow), title (24/600), sub line, actions on the right; optional session rail.',
    ['Default', '`small`: icon becomes a 24px corner mark (Patient Mobile home)', '`rail: [done, total]`: one rail segment per session'],
    ['Buttons on it use the `light` variant'],
    'brand-600, brand-500, brand-100, brand-200, surface, radius-hero',
    ['Use it for identity areas (patient home, welcome)', 'Keep text short: title, one sub line, one action'],
    ['Never place it behind tables, prescriptions or doctor notes', 'Do not stack two heroes on a page'],
    'Web-only use; the app uses it on home tabs. Padding 24, title 24.',
    'Patient Mobile frames: title 21, max width 290, kicker tracking .06em; actions go below the text.',
  ),
  kpis: c(
    'Row of 1-6 tiles; each tile: label (label 12, ink-soft) with optional icon, value (metric 27/700, heading), optional unit, note (label 12).',
    ['`tone` of the note: neutral, success, warning, danger', 'With `unit`, `icon`, `chev`', 'With `actions: [btn]` under the note'],
    ['A tile that is a link shows no hover change on the canvas; the kit tile is static'],
    'surface, line, shadow-card, radius-card, heading, ink-soft, success/warning/danger (note only)',
    ['Say what the number is in the label', 'Colour only the note; the value stays heading colour'],
    ['Do not colour the value red or green instead of writing the status', 'Do not put more than 6 tiles in one row'],
    'N columns in one row, gap 16 (1440) or 20 (1920), padding 19/20.',
    'Two tiles per row, padding 14.',
  ),
  stat: c(
    'Label (label 12, ink-soft), value (section 16/700, heading) with optional unit (small), optional sub line.',
    ['With or without unit', 'With sub line'],
    NONE_STATE,
    'ink-soft, heading, text-label, text-section',
    ['Use for a small summary cell inside a `grid(3, ...)`', 'Keep values short (a count, a date)'],
    ['Do not use it where a `kpis` tile fits (a top-of-page metric)'],
    'Plain text cell, no border.',
    'Cells stack according to the parent `grid` (`colsn`).',
  ),
  chips: c(
    'Row of filter pills; each pill: label, optional count bubble.',
    ['Horizontal (default)', '`vert`: stacked, label left and count right', 'Item `sel` (selected), `dis` (disabled), plain'],
    ['Default: surface, line, ink-soft', 'Selected: brand-500 fill, white text, count on brand-100', 'Disabled: 50% opacity'],
    'surface, line, ink-soft, tile, brand-500, brand-100, brand-700, radius-pill',
    ['Use `Tất cả` as the first chip of a filter', 'Show the count when the list is long'],
    ['Do not use chips for navigation (tabs) or for a status (badge)'],
    'Height 36.',
    'Height 40 on the canvas (44 in the kit); the row wraps.',
  ),
  tags: c(
    'Wrapping row of badges as one leaf.',
    ['Any mix of badge tones'],
    NONE_STATE,
    'See badge',
    ['Use for hero or card chips (two or three at most)'],
    ['Do not use it for filters (chips)'],
    'Gap 6, wraps.',
    SAME,
  ),
  tabs: c(
    'Bar of items; each item: label, optional count; active item has a 2px underline in link colour and 700 weight.',
    ['Underline bar (default)', '`seg`: segmented control (Ngày / 7 ngày), pills inside a tile-coloured track'],
    ['Active: link colour, 700, underline', 'Inactive: ink-soft', 'Keyboard: arrow keys, Home, End (kit)'],
    'link, ink-soft, line, tile, surface, shadow-card (active segment)',
    ['Use for views of the same object (Patient 360)', 'Keep labels to one or two words; give a `shortLabel` for 390'],
    ['Do not use tabs for filters (chips) or for steps of a flow'],
    'Underline bar, items 40px high, left aligned.',
    'Becomes a segmented control of equal pills with short labels; the active pill is raised (surface, shadow-card).',
  ),
  notice: c(
    'Icon, optional bold title, text, optional bullet list (with a bold list title), optional buttons.',
    ['Tone: info, warning, danger, success', 'With `items`, with `actions`'],
    ['Static. A danger notice is announced as an alert in the kit (role alert)'],
    'info/warning/danger/success with -soft and -line, radius-tile',
    ['Keep the old text verbatim', 'One notice per message'],
    ['Do not use danger for a boxed hint that is only information', 'Do not put fields inside (use `box`)'],
    'Padding 8/12, icon 18. Kit names the tones `info`, `warn`, `error`, `success`; the canvas says `warning` and `danger`.',
    SAME,
  ),
  facts: c(
    'Rows with label on the left (ink-soft) and value on the right (600, ink) with an optional small sub line; divider between rows.',
    ['With or without sub line'],
    NONE_STATE,
    'ink-soft, ink, line',
    ['Use for key facts of one object (patient, invoice)'],
    ['Do not use for 3+ comparable rows (table)'],
    'Value right aligned.',
    SAME,
  ),
  field: c(
    'Label (label 12/600, ink-soft, optional red asterisk), control, hint, error line. Controls: input, select, date, time, month, number, textarea, check, radio, search, file, range.',
    ['Text-like (input, number, date, time, month, search)', 'select (with open option list)', 'textarea (`lines`)', 'check, radio', 'range, file'],
    ['Default: line-strong border, field fill', 'Focus: brand-500 border and ring (kit)', 'Error: danger border and message', 'Disabled: 60% opacity', 'Checked: brand-500 fill'],
    'field, line-strong, ink, ink-soft, danger, brand-500, radius-field, text-body-lg (value), text-label (label)',
    ['Label verbatim from the old screen', 'Show the hint under the control and the error replacing nothing (both can show)'],
    ['Do not use a placeholder as the label', 'Do not hide the label on a phone'],
    'Control min-height 40; `w` sets a width in a row.',
    'Controls take the full row width.',
  ),
  table: c(
    'Wrapper with a header row (micro, uppercase, table-head fill), data rows with dividers, optional footer row.',
    ['Up to 7 columns', '`foot` summary row', '`empty`: single empty row', 'Row hover fill for a clickable row'],
    ['Hover: row-hover (clickable rows)', 'Empty row: centred ink-soft text'],
    'surface, line, table-head, row-hover, ink-soft, text-micro, text-body, radius-card',
    ['Use for 3+ comparable rows', 'Put the main identifier in the first column'],
    ['Do not use more than 7 columns', 'Do not use a table for two or three facts (facts)'],
    'Grid columns by `cols`; padding 12/16.',
    'Header hides; every row becomes a card, the first cell is the title and each other cell shows its column label above its value.',
  ),
  empty: c(
    'Optional icon tile (brand-50), title (body-lg 600), hint (body, ink-soft, max 420), optional actions.',
    ['Default card', '`flat`: no card chrome, centred grey text inside a card'],
    NONE_STATE,
    'surface, line, shadow-card, brand-50, brand-500, ink, ink-soft',
    ['Say what is missing and the one action that fixes it'],
    ['Do not apologise or explain at length', 'Do not offer two equal primary actions'],
    'Padding 40/24.',
    SAME,
  ),
  bars: c(
    'Rows: label and count on one line, bar under it (8px, tile track, tone fill).',
    ['Tone: success, warning, danger, info (brand when none)'],
    NONE_STATE,
    'tile, brand-500, success, warning, danger, info, heading (count)',
    ['Use for one distribution (appointments by status)', 'Write the count next to the bar'],
    ['Do not show a bar without its number'],
    'Rows stacked, gap 12.',
    SAME,
  ),
  timeline: c(
    'Vertical list; each item: round icon dot (32px) joined by a 2px line, date (micro, uppercase), title (600), detail, "by" line.',
    ['Dot tone: brand (default), success, warning, danger'],
    NONE_STATE,
    'brand-50, brand-100, brand-500, line, ink, ink-soft, success/warning/danger with -soft and -line',
    ['Newest first or oldest first, one order per screen', 'Name who did it in the "by" line'],
    ['Do not use it for a form wizard'],
    'Dot 32, connector at left 15.',
    SAME,
  ),
  list: c(
    'Rows with optional number, icon or avatar on the left, text (optional over line, title 600, sub lines) and actions or a chevron on the right.',
    ['Plain divided rows (default)', '`box`: bordered rows', '`plain`: text lines (guide steps)', '`ordered`: numbered', '`sq` + `chev`: Patient Mobile document row'],
    ['Static on the canvas; a clickable row is a link in the kit'],
    'line, brand-50, brand-500, brand-700, ink, ink-soft, surface, radius-tile (box, sq)',
    ['Use for 1-6 simple rows or when a table has one useful column', 'Put money or a status in `actions`'],
    ['Do not use for 3+ rows that need several comparable columns (table)'],
    'Row padding 10/0 (box rows 12/14).',
    SAME,
  ),
  board: c(
    'Rooms across the top, time down the left in a 56px column, booking blocks placed by start and length; optional buffer block and free-slot buttons.',
    ['Booking colour by service 0-3 (info, brand, success, warning)', 'Buffer: dashed hatched block', 'Free slot: dashed "Đặt lịch" button'],
    ['Slot is a button; others static'],
    'surface, line, table-head, tile, info/brand/success/warning (booking colours), radius-tile, radius-field',
    ['Show the service legend (the board adds it)', 'Mark the 15 minute room preparation as a buffer'],
    ['Do not use it outside scheduling'],
    'Web-only. Hour height `hh`.',
    'One list per room.',
  ),
  weekGrid: c(
    'Seven day columns, each with a header and booking cards and an "Đặt lịch" button.',
    ['Booking colour by service'],
    ['Day button is a button; others static'],
    'field, line, radius-tile, service colours',
    ['Use for the week view of the schedule'],
    ['Do not use it for a month view'],
    'Web-only. Seven equal columns.',
    'One list per day.',
  ),
  photos: c(
    'Grid of 3:2 placeholder tiles with the tag "MINH HỌA TỔNG HỢP", label and meta under each.',
    ['Default', '`empty: true` (missing photo)', '`slider: true` (compare slider)', '`sq`: square tiles, tag at the bottom'],
    NONE_STATE,
    'tile, brand-100, brand-500, line, surface, ink-soft, radius-tile',
    ['Always keep the tag "MINH HỌA TỔNG HỢP"', 'Placeholders only'],
    ['Never show real or generated faces, never score improvement from a placeholder'],
    'Gap 16.',
    'Grid follows the parent (usually 2 columns).',
  ),
  a5: c(
    'Paper sheet 148 x 210: header with logo, title, draft stamp, fields grid, items, note, signature block.',
    ['Prescription, consultation form (content by `rows`, `items`)'],
    NONE_STATE,
    'plate, line-strong, ink, heading, link, warning (draft stamp)',
    ['Two per row in `grid(2, ...)`', 'Stays white in dark mode'],
    ['Do not use it as a screen layout'],
    'Web-only print sheet.',
    'Not drawn at 390.',
  ),
  img: c(
    'Rounded neutral box with an icon and a label.',
    ['Height by `h`'],
    NONE_STATE,
    'tile, line, ink-soft, brand-500 (icon, 60%)',
    ['Use where a real image will go'],
    ['Do not use it as a photo of a person'],
    'Fixed height.',
    SAME,
  ),
  legend: c(
    'Row of square swatches (outline in the service colour) with the service name.',
    ['Four service colours'],
    NONE_STATE,
    'ink-soft, info/brand/success/warning',
    ['Show it with any board that colours by service'],
    ['Do not rely on colour alone: the booking card names the service'],
    'Wraps.',
    SAME,
  ),
  sp: c('An empty vertical gap of `h` px.', ['Any height'], NONE_STATE, 'none (use the space scale)', ['Use only when `stack` gap is not enough'], ['Do not use it to push content to the bottom'], 'Vertical.', SAME),
  hr: c('A 1px line.', ['One'], NONE_STATE, 'line', ['Use between groups inside a card'], ['Do not use it between cards'], 'Full width.', SAME),
  code: c('Monospace block with pre-wrapped text.', ['One'], NONE_STATE, 'field, line, ink, radius-tile, text-label', ['Use for raw text such as a tool call'], ['Do not use it for normal copy'], 'Padding 12.', SAME),
  stack: c('Vertical flex container.', ['`g` gap, default 12'], NONE_STATE, 'space-3 (default gap)', ['Nest at most four containers deep'], ['Do not use margins; use `g`'], 'Column.', SAME),
  row: c('Horizontal flex container that wraps.', ['`g` gap, `ai` align-items, `jc` justify-content'], NONE_STATE, 'space scale', ['Use for buttons and fields on one line'], ['Do not nest a `row` in a `row` for layout'], 'Wraps when the line is full.', 'Wraps; fields take the full width.'),
  grid: c(
    'CSS grid container.',
    ['`cols` number or template', '`colsn` template at 390', '`split(main, aside)`: main column 1.65fr, aside 1fr (min 300)'],
    NONE_STATE,
    'space scale, layout-aside-w',
    ['Use `split` for a main area and a side card', 'Four or more equal columns become two at 390'],
    ['Do not use a grid for a list of rows (list or table)'],
    'Columns as given.',
    'One column unless `colsn` says otherwise (two for 4+ equal columns).',
  ),
  card: c(
    'Optional eyebrow, title (body-lg 700, heading), sub line (label 12), `aside` blocks on the right, then children.',
    ['`v`: panel (default), soft, ai, plain, flush, hero', '`tint`: info, brand, success, warning, danger or service 0-3', '`comp`: composition card (see ScheduleJobCard ... TemplateCard)'],
    ['Static; the title takes the tint colour when tinted'],
    'surface, line, shadow-card, radius-card, field (soft), brand-50 (ai), heading',
    ['Group one topic per card', 'Put a table in `flush` so it touches the edges'],
    ['Do not wrap every label in a card', 'Do not nest cards more than once'],
    'Padding 20 (hero 20/24, ai 18, soft 14).',
    'Panel padding 16.',
  ),
  box: c(
    'Callout with a left-aligned title (small 600) and children such as fields, badges and buttons.',
    ['Tone: info, warning, danger, success, neutral'],
    NONE_STATE,
    'info/warning/danger/success with -soft and -line, tile, radius-tile',
    ['Use when a notice must contain controls'],
    ['Do not use for plain text (notice)'],
    'Padding 12/14.',
    SAME,
  ),
  disc: c(
    'Bordered card with a summary row (link colour, plus sign) and a body drawn open.',
    ['Open (the canvas always draws it open)'],
    ['Closed and open in the product; the canvas shows open'],
    'surface, line, shadow-card, link',
    ['Use for optional forms such as "+ Ghi nhận lượt thủ thuật…"'],
    ['Do not hide required fields in it'],
    'Summary padding 14/20.',
    SAME,
  ),
  txt: c(
    'Inline text with size, tone, weight; parts can carry flags (bold, small, uppercase, soft, danger, success, warning, link, heading).',
    ['`sm` (small ink-soft), `lbl` (label ink-soft), `strong`, `eyebrow`, `kv` (bold label then value)'],
    NONE_STATE,
    'ink, ink-soft, heading, link, success, warning, danger, info, text scale',
    ['Use the helper that names the role (`sm`, `lbl`)'],
    ['Do not pass a colour or a pixel size; use `tone` and `size`'],
    'Newlines are kept (pre-line).',
    SAME,
  ),
  btn: c(
    'Optional leading icon, label, optional trailing icon. Icon-only button has an accessible name (`aria`).',
    ['primary', 'secondary', 'danger (outlined)', 'dangers (solid)', 'quiet (text, link colour)', 'link', 'light (on a hero)', 'size `sm`, `full` width, icon-only'],
    ['Default', 'Hover: primary darkens to brand-600, secondary fills tile, danger fills danger-soft, quiet underlines (kit)', 'Focus: focus ring', 'Disabled: 50% opacity, no pointer'],
    'brand-500, brand-600, surface, line-strong, ink, danger, danger-line, link, brand-50 (light), radius-control, text-small',
    ['One primary per view or dialog footer, on the right', 'Label is the action ("Lưu", not "OK")'],
    ['Do not use two primaries together', 'Do not use danger for a harmless action'],
    'Height 40 (sm 32), padding 0 14, radius 10.',
    'Height 44 (sm 36); long labels wrap and centre.',
  ),
  badge: c(
    'Dot (6px, optional) and a status word in a pill.',
    ['Tone: neutral, brand, info, success, warning, danger'],
    NONE_STATE,
    'tile/ink-soft (neutral), brand-50/brand-700, and -soft/-line/text of each status; radius-pill, text-label',
    ['The text is the status; colour only supports it'],
    ['Do not use colour alone', 'Do not use it as a button'],
    'Padding 2/10.',
    SAME,
  ),
  avatar: c('Circle with initials.', ['sm 28, md 34, lg 64'], NONE_STATE, 'brand-50, brand-100, brand-700, radius-pill', ['Use two letters of the name'], ['Do not use a photo of a real person on the canvas'], 'Inline.', SAME),
  icon: c(
    'Material Symbols Outlined glyph by name.',
    ['Size 16, 20, 24, 32', 'Tone like text'],
    NONE_STATE,
    'ink-soft (default), the text tones',
    ['Pair an icon-only control with an accessible name'],
    ['A wrong name shows as text; `check` reports it (`badIcons`)', 'Do not use emoji as icons'],
    'Inline. The kit uses its own SVG set (`icons.tsx`).',
    SAME,
  ),
  chip: c(
    'Single filter pill.',
    ['Selected (`sel`), disabled (`dis`), plain; optional count'],
    ['As chips'],
    'See chips',
    ['Use `chips` for a group'],
    ['Do not use a lone chip as a status'],
    'Height 36.',
    'Height 40.',
  ),
  prog: c(
    'Track (8px, tile) and fill, optional label above.',
    ['Tone: brand (default), success, warning, danger, info'],
    NONE_STATE,
    'tile, brand-500, success, warning, danger, info, ink-soft',
    ['Show the percent or fraction in words next to it'],
    ['Do not use it as a skin-improvement score'],
    'Fills the row.',
    SAME,
  ),
  appt: c(
    'Date tile (58 x 60, brand-50: day 20/700 over month in uppercase), bold title, grey lines.',
    ['Dated', '`none: true`: calendar icon and "Chọn lịch"'],
    NONE_STATE,
    'brand-50, brand-100, brand-700, ink, ink-soft, radius-tile',
    ['Put it in a card ("Lịch hẹn tiếp theo")'],
    ['Do not use it for a booking on a board (board)'],
    'Web-only body. Tile 58 x 60.',
    SAME,
  ),
  events: c(
    'Rows with icon by kind (followup, photo, done), date, bold title, chevron; an open row shows its detail.',
    ['`open: true` expands a row'],
    ['Closed: detail hidden', 'Open: detail below, indented 48'],
    'brand-50, brand-500, line, ink, ink-soft',
    ['Use for "Cập nhật gần đây" on the journey'],
    ['Do not show the detail of a closed row'],
    'Min row height 72.',
    SAME,
  ),
  bubbles: c(
    'Chat bubbles with optional sender name, text, time line, optional italic note. Customer left (tile), own or bot right (info-soft).',
    ['`mine: true` right and tinted'],
    NONE_STATE,
    'tile, info-soft, ink, ink-soft, radius-card',
    ['Show the time under the text', 'In the agent chat the customer is left and the bot right'],
    ['Do not use it for a notice'],
    'Max width 94%.',
    SAME,
  ),
  upload: c(
    'Dashed box: camera icon, hint, "Chọn ảnh" button, chosen file name, status line, optional synthetic preview with the tag "MINH HỌA TỔNG HỢP".',
    ['Empty', 'File chosen with status', 'With preview'],
    ['Empty: dashed line-strong border', 'Chosen: file name 600 and status micro'],
    'field, line-strong, ink-soft, ink, brand-100, brand-500, radius-card',
    ['Say the file is kept for the demo session when it is'],
    ['Never preview a real photo'],
    'Preview 180 x 120.',
    SAME,
  ),
  stepper: c(
    'Label ("2/5 buổi"), progress bar, caption "Tiến độ số buổi, không phải mức cải thiện da."',
    ['One'],
    NONE_STATE,
    'heading (label 20/700), tile, brand-500, ink-soft',
    ['Count sessions only'],
    ['Never turn it into an improvement score'],
    'Bar fills the row.',
    SAME,
  ),
  quick: c(
    'Row of tiles; each: icon (brand-500), bold title (label), sub line (micro).',
    ['2-4 tiles'],
    ['Tiles are buttons in the product'],
    'brand-50, brand-500, brand-700, ink-soft, radius-tile',
    ['Use for the three or four most common actions on home'],
    ['Do not use it for navigation (menu)'],
    'Equal columns, min height 92.',
    SAME,
  ),
  rx: c(
    'Card "Đơn & phiếu đã duyệt" with a count chip and one section per approved prescription or order (groups "Đơn thuốc" / "Phiếu tư vấn").',
    ['With sections', 'Pending / empty: chip "Chưa có" and the sentence "Đơn và phiếu sẽ xuất hiện sau khi bác sĩ duyệt."'],
    NONE_STATE,
    'heading, ink, ink-soft, line, text-body-lg, text-label',
    ['List only approved items'],
    ['Never list a prescription that the doctor has not approved'],
    'Sections divided by a line.',
    SAME,
  ),
  matrix: c(
    'Table whose cells can hold fields: a select, a number input with suffix, a checkbox, or inline blocks.',
    ['Select cell (`mxSel`)', 'Input cell (`mxIn`, with `ph`, `suf`)', 'Check cell (`mxCk`)'],
    ['As field states inside a cell'],
    'table tokens + field tokens, text-body, text-label',
    ['Give every field cell an accessible name (`label`)'],
    ['Do not use it for read-only data (table)'],
    'Web-only. Input max width 200, min height 34.',
    'Rows become cards like a table.',
  ),
  trace: c(
    'One header button per run ("Xem" / "Thu gọn"), and for an open run its steps: finish reason, tokens in/out, tool call (mono), tool answer, model text.',
    ['Closed run', 'Open run with steps'],
    ['Open: header on table-head fill with a line under it'],
    'surface, line, table-head, field, ink, ink-soft, radius-card, radius-tile',
    ['Show raw tool call and answer in monospace'],
    ['Do not show personal data; the canvas uses synthetic text'],
    'Web-only.',
    SAME,
  ),
  errLine: c(
    'Error icon and danger text, no box.',
    ['One'],
    ['Announced as an alert in the product'],
    'danger',
    ['Put it last in a dialog body or under the tabs it belongs to'],
    ['Do not use it for a boxed notice (notice danger)'],
    'Text 13, icon 18.',
    SAME,
  ),
};

// Composition blocks have no markup of their own: `card({ comp: '<Name>' })` with the children listed in BLOCKS.md.
const comp = (what, kit, states, dos) =>
  c(
    `A \`card\` (\`comp: '${what}'\`) that holds ${kit}`,
    ['As listed in the rules of BLOCKS.md'],
    states,
    'card tokens + the tokens of its badges, buttons and fields',
    dos,
    ['Do not draw it with new markup; compose it from card, badge, button, field'],
    'A card in the frame grid.',
    SAME,
  );

DATA.ScheduleJobCard = comp('ScheduleJobCard', 'a bold title, status badges, a grey line, an optional danger notice with the last error and the run buttons.', ['Failed job shows the danger notice', 'Buttons follow button states'], ['Show the last error in words']);
DATA.KbChunkCard = comp('KbChunkCard', 'a bold path and a small text, `v: soft`.', NONE_STATE, ['Keep the path verbatim']);
DATA.ChannelSettingsCard = comp('ChannelSettingsCard', 'one Zalo channel: badges, the "Bật kênh <tên>" switch, daily cap, spacing, send window and the emergency-switch notice.', ['Locked when the emergency switch is on'], ['Show the emergency state as a notice']);
DATA.AccountCard = comp('AccountCard', 'one Zalo account: badges, the "Bật account <tên>" switch, extra buttons (Login QR), "Sửa", "Xóa".', ['Buttons follow button states'], ['Keep "Xóa" as a danger button']);
DATA.ChannelCard = comp('ChannelCard', 'the channel panel of the Zalo accounts page and its locked state.', ['Locked (emergency switch on)'], ['Say why it is locked']);
DATA.AccountRow = comp('AccountRow', 'one account row with its agent ("brain"), policy profile and status.', NONE_STATE, ['Show the policy profile as a badge']);
DATA.AgentCard = comp('AgentCard', 'icon and name, badges, id, cut persona, accounts in use, "Xem chi tiết", "Sửa" and the row menu.', ['Buttons follow button states'], ['Cut a long persona with an ellipsis']);
DATA.AgentRow = comp('AgentRow', 'the list view of an agent with an avatar.', NONE_STATE, ['Use it for the list view, AgentCard for the grid']);
DATA.ToolRow = comp('ToolRow', 'name, code id, description, state badges, an optional "Settings" link and the switch "Bật tắt <tên>".', ['Switch on / off'], ['Name the switch with the tool name']);
DATA.TuningNavItem = comp('TuningNavItem', 'one of the six groups of "Mô hình & cấu hình"; the active one is `v: soft`, `tint: info`.', ['Active: soft card, info tint', 'Inactive: plain card'], ['Mark the active group visibly']);
DATA.TuningGroup = comp('TuningGroup', 'tuning parameters: description with a "mặc định" / "Tùy chỉnh" badge on the left, a labelled field with its range hint on the right, rows divided by `hr`.', ['Parameter at default or customised (badge)'], ['Show the allowed range as a hint']);
DATA.StaffCard = comp('StaffCard', 'name, "{vai trò} · đang giữ n/m cuộc trò chuyện", "Sửa", skill badges or "Chưa có kỹ năng", weekly shifts or "Chưa có ca".', ['Empty skills and shifts have their own sentences'], ['Write the empty sentences']);
DATA.OnCallCard = comp('OnCallCard', 'name, number, validity, status badges and "Sửa".', ['Active / expired badges'], ['Show validity in words']);
DATA.AlertCard = comp('AlertCard', 'a kind badge, a link to the patient care timeline, an optional detail and the time.', NONE_STATE, ['Link to the patient']);
DATA.HandoffCard = comp('HandoffCard', 'patient link, age and step, urgency and depth badges, bold reason, summary, needed skill, confidence, SLA, optional error and the two actions; `tint: danger` when urgent.', ['Urgent: danger tint', 'Error line when the handoff failed'], ['Show the SLA']);
DATA.TemplateCard = comp('TemplateCard', 'heading, key, status badges ("Bác sĩ đã duyệt" / "Chờ bác sĩ duyệt" / "Quảng bá"), body, approval line and the buttons the role may use.', ['Approved / waiting for the doctor / promotional'], ['Show only the buttons the role may use']);

module.exports = { DATA };
