# ported from: src/knowledge/kb-file-store.ts
"""Write/delete the ORIGINAL file of a knowledge-base source under ``<data_dir>/kb/``.

The file name a user picks NEVER touches the real path: ``luu_file`` takes an id generated by the CALLER (not
the original name of the user's file) and still filters it again with ``segment_an_toan`` in case that id
carries odd characters - two layers of defence for the same kind of invariant as ``sanitizeSegment`` of
``media-store``.

Forced deviation: ``dataDir`` of the original is ``Settings.data_dir`` (``PEMA_DATA_DIR``, a local volume).
WHERE the files live in production (a local volume shared by the API and the worker process, or object
storage) is an open item of the plan (CONTRACTS-AI01 section 9); this module is the only place to change when
it is decided, and the value stored in ``agent.kb_document.storage_key`` is the relative path
``kb/<id>.<format>`` either way. Reads/writes are synchronous file operations: async callers run them with
``asyncio.to_thread``.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Final

from pema.config.env import get_settings

KB_DIR: Final = "kb"


def _goc(data_dir: Path | None) -> Path:
    return data_dir if data_dir is not None else get_settings().data_dir


def segment_an_toan(gia: str) -> str:
    """Keep only characters safe for a file name - blocks ``..``, ``/``, ``\\`` escaping the folder."""
    return re.sub(r"[^a-zA-Z0-9_-]", "_", gia) or "x"


def luu_file(source_id: str, dinh_dang: str, buf: bytes, *, data_dir: Path | None = None) -> str:
    """Save the buffer to ``<data_dir>/kb/<id>.<format>``. Returns the path RELATIVE to ``data_dir`` (always
    with ``/``, not the OS separator - this is the value stored in the ``storage_key`` column so it must be
    stable between machines)."""
    thu_muc = _goc(data_dir) / KB_DIR
    thu_muc.mkdir(parents=True, exist_ok=True)
    rel_path = f"{KB_DIR}/{segment_an_toan(source_id)}.{segment_an_toan(dinh_dang)}"
    (_goc(data_dir) / rel_path).write_bytes(buf)
    return rel_path


def doc_file(duong_dan_tuong_doi: str, *, data_dir: Path | None = None) -> bytes:
    """Read a stored file by the RELATIVE path kept in ``storage_key``. Refuses a path that escapes
    ``<data_dir>/kb`` (the value comes from the database, but a row is not a reason to trust a path)."""
    goc_kb = (_goc(data_dir) / KB_DIR).resolve()
    dich = (_goc(data_dir) / duong_dan_tuong_doi).resolve()
    if goc_kb not in dich.parents:
        raise ValueError("Đường dẫn file nằm ngoài thư mục kho tri thức")
    return dich.read_bytes()


def xoa_file(duong_dan_tuong_doi: str, *, data_dir: Path | None = None) -> None:
    """Delete a file by the RELATIVE path stored in ``storage_key``. Idempotent: an empty path (a hand typed
    source that never wrote a file) or a file already gone is not an error - the delete route must not break
    because the disk and the database disagree."""
    if not duong_dan_tuong_doi:
        return
    goc_kb = (_goc(data_dir) / KB_DIR).resolve()
    dich = (_goc(data_dir) / duong_dan_tuong_doi).resolve()
    if goc_kb not in dich.parents:
        return
    dich.unlink(missing_ok=True)
