plugins:
  riverpod_lint: ^3.1.9

analyzer:
  errors:
    unused_import: warning
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**

# const widgets are created once and skipped on rebuild.
linter:
  rules:
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
