/* Deterministic domain/transaction regression tests; no browser required. */
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const results=[];
function boot(saved=null){
 let stored=saved;const listeners={};
 const ctx={console,crypto,structuredClone,Event:class{constructor(type){this.type=type}},CustomEvent:class{constructor(type,options){this.type=type;this.detail=options.detail}},localStorage:{getItem:()=>stored,setItem:(k,v)=>stored=v},addEventListener:(k,f)=>(listeners[k]||=[]).push(f),dispatchEvent:e=>(listeners[e.type]||[]).forEach(f=>f(e))};ctx.window=ctx;
 vm.createContext(ctx);for(const f of ['data.js','operations-data.js','crm-data.js','crm-automation.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'shared',f),'utf8'),ctx,{filename:f});ctx.PemaCRM.ensure();return ctx;
}
function check(name,fn){try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.stack});}}
const payload={channel:'Gọi điện',outcome:'no_need',owner:'CSKH Mai Anh',note:'Khách đã xác nhận nhu cầu trong cuộc gọi mô phỏng',priority:'normal'};
const task=(x,type,p)=>x.Pema.state.crmTasks.find(t=>t.type===type&&(!p||t.patientId===p)&&x.PemaCRM.open(t));
check('all ten rules, eight cases, 36 synthetic patients',()=>{const x=boot();assert.equal(x.Pema.state.patients.length,36);assert.equal(x.Pema.state.patients.filter(p=>p.crm.demoCase).length,8);assert.equal(new Set(x.Pema.state.crmTasks.map(t=>t.ruleId)).size,10);});
check('automation rerun and reload never duplicate tasks',()=>{const x=boot(),before=JSON.stringify(x.Pema.state.crmTasks);x.PemaCRM.ensure();x.PemaCRM.ensure();assert.equal(JSON.stringify(x.Pema.state.crmTasks),before);assert.equal(JSON.stringify(boot(JSON.stringify(x.Pema.state)).Pema.state.crmTasks),before);});
check('D+1/D+3/D+7 from completed protocol sessions only',()=>{const x=boot();for(const [p,type]of[['P025','d1'],['P026','d3'],['P032','d7']])assert(task(x,type,p));assert(!task(x,'d1','P001'));});
check('expected visit overdue is 14 days with doctor source',()=>{const x=boot(),c=x.PemaCRM.profile(x.Pema.patient('P027'));assert.equal(c.overdueDays,14);assert.equal(c.expectedVisitSource,'doctor_recommendation');});
check('unfinished six-session plan and sixty-day gap',()=>{const x=boot(),p=x.Pema.patient('P029');assert.equal(p.total-p.completed,3);assert(task(x,'abandoned',p.id));});
check('no-show and cancellation older than 24h without future booking',()=>{const x=boot();assert(task(x,'no_show','P028'));assert(!task(x,'no_show','P001'));});
check('dormant90/180 are exclusive per customer',()=>{const x=boot();assert(task(x,'dormant180','P030'));assert(!task(x,'dormant90','P030'));assert(task(x,'dormant90','P031'));});
check('birthday window handles year boundary and excludes past birthdays',()=>{const x=boot();assert(task(x,'birthday','P032'));x.Pema.patient('P001').crm.birthday='1990-09-19';x.PemaCRM.run();assert(!task(x,'birthday','P001'));});
check('resolve persists one activity, timeline and metrics',()=>{const x=boot(),t=task(x,'overdue','P027'),m=x.PemaCRM.metrics();x.PemaCRM.resolve(t.id,payload);assert.equal(x.PemaCRM.metrics().completed,m.completed+1);assert.equal(x.PemaCRM.metrics().pending,m.pending-1);assert(x.PemaCRM.timeline(x.Pema.patient(t.patientId)).some(a=>a.source===t.id));assert.throws(()=>x.PemaCRM.resolve(t.id,payload));});
check('callback requires next action and reschedules without duplicate',()=>{const x=boot(),id=task(x,'d1','P025').id;assert.throws(()=>x.PemaCRM.resolve(id,{...payload,outcome:'callback'}));x.PemaCRM.resolve(id,{...payload,outcome:'callback',nextActionAt:'2026-09-21T10:30',nextActionType:'call'});assert.equal(x.Pema.state.crmTasks.find(t=>t.id===id).status,'rescheduled');assert(!x.PemaCRM.queue().some(t=>t.id===id));x.PemaCRM.ensure();assert.equal(x.Pema.state.crmTasks.filter(t=>t.id===id).length,1);});
check('booking validates conflicts before atomic CRM resolution',()=>{const x=boot(),id=task(x,'dormant90','P031').id,crmInput={...payload,outcome:'booked'},before=JSON.stringify(x.Pema.state);assert.throws(()=>x.PemaOps.saveAppointment({patient:'P031',service:'S0',doctor:'D0',room:'R0',date:'2026-09-20',time:'08:00',crmTaskId:id,crmInput}),/Trùng/);assert.equal(JSON.stringify(x.Pema.state),before);});
check('booking links appointment and expected visit without fake reactivation',()=>{const x=boot(),id=task(x,'dormant90','P031').id,m=x.PemaCRM.metrics();const a=x.PemaOps.saveAppointment({patient:'P031',service:'S0',doctor:'D0',room:'R0',date:'2026-09-27',time:'10:00',crmTaskId:id,crmInput:{...payload,outcome:'booked'}});assert.equal(x.Pema.state.crmTasks.find(t=>t.id===id).relatedAppointmentId,a.id);assert.equal(x.PemaCRM.profile(x.Pema.patient('P031')).expectedNextVisitAt,'2026-09-27');assert.equal(x.PemaCRM.metrics().booked,m.booked+1);assert.equal(x.PemaCRM.metrics().reactivated,0);assert.equal(x.Pema.state.crmActivities[0].relatedAppointmentId,a.id);});
check('booking mismatch, missing note and duplicate task are rejected',()=>{const x=boot(),id=task(x,'dormant90','P031').id;assert.throws(()=>x.PemaOps.saveAppointment({patient:'P030',service:'S0',doctor:'D0',room:'R0',date:'2026-09-27',time:'10:00',crmTaskId:id,crmInput:{...payload,outcome:'booked'}}),/đúng bệnh nhân/);assert.throws(()=>x.PemaCRM.resolve(id,{...payload,note:''}));});
check('opt-out suppresses marketing, retains clinical tasks and trace',()=>{const x=boot(),id=task(x,'dormant180','P030').id;x.PemaCRM.resolve(id,{...payload,outcome:'optout'});assert(x.Pema.patient('P030').crm.marketingOptOut);assert(!x.PemaCRM.queue().some(t=>t.patientId==='P030'&&t.type==='dormant180'));assert(task(x,'abandoned','P030'));});
check('reaction / complaint escalates to clinical inbox, never auto-reviewed',()=>{const x=boot();x.PemaCRM.resolve(task(x,'d1','P025').id,{...payload,outcome:'reaction'});const f=x.Pema.state.followups[0];assert.equal(f.status,'open');assert.equal(f.patient,'P025');assert(!f.reviewedBy);assert.equal(x.Pema.patient('P025').messages.length,1);});
check('failed storage rolls back appointment, task, activity and expected date',()=>{const x=boot(),before=JSON.stringify(x.Pema.state),id=task(x,'dormant90','P031').id,save=x.Pema.save;x.Pema.save=()=>false;assert.throws(()=>x.PemaOps.saveAppointment({patient:'P031',service:'S0',doctor:'D0',room:'R0',date:'2026-09-27',time:'10:00',crmTaskId:id,crmInput:{...payload,outcome:'booked'}}));x.Pema.save=save;assert.equal(JSON.stringify(x.Pema.state),before);});
check('reset produces identical tasks/metrics regardless of activities',()=>{const x=boot(),before=JSON.stringify({t:x.Pema.state.crmTasks,m:x.PemaCRM.metrics()});x.PemaCRM.resolve(task(x,'d1','P025').id,payload);x.Pema.reset();x.PemaCRM.ensure();assert.equal(JSON.stringify({t:x.Pema.state.crmTasks,m:x.PemaCRM.metrics()}),before);});
check('legacy migration preserves clinical and payment history',()=>{const x=boot(),s=JSON.parse(JSON.stringify(x.Pema.state));delete s.crmVersion;delete s.crmFixturePending;for(const p of s.patients)delete p.crm;const before=JSON.stringify(s.patients.map(p=>[p.sessions,p.invoices,p.events]));const y=boot(JSON.stringify(s));assert.equal(JSON.stringify(y.Pema.state.patients.map(p=>[p.sessions,p.invoices,p.events])),before);});
check('payment and CRM do not approve draft prescriptions or complete sessions',()=>{const x=boot(),p=x.Pema.patient('P002'),count=p.completed;p.prescriptions=[{id:'draft',status:'draft'}];x.Pema.save();x.PemaOps.pay('P002','HD-DEMO-002',1000,'Tiền mặt');assert.equal(x.Pema.patient('P002').completed,count);assert.equal(x.Pema.patient('P002').prescriptions[0].status,'draft');});
check('new protocol completion schedules future D+1/3/7 without adding them to due queue',()=>{const x=boot(),p=x.Pema.patient('P001');p.sessions.push({id:'new-session',date:'2026-09-20',protocolId:'laser-co2'});x.PemaCRM.run();const tasks=x.Pema.state.crmTasks.filter(t=>t.sourceEventId==='new-session');assert.equal(tasks.length,3);assert(tasks.some(t=>t.dueAt.startsWith('2026-09-21')));assert(!x.PemaCRM.queue().some(t=>t.sourceEventId==='new-session'));});
check('recall respects actual 24-hour boundary, not calendar day alone',()=>{const x=boot(),p=x.Pema.patient('P036');x.Pema.state.operations.appointments=x.Pema.state.operations.appointments.filter(a=>a.patient!==p.id);x.Pema.state.operations.appointments.push({id:'recent-cancel',patient:p.id,date:'2026-09-19',time:'17:00',status:'cancelled',cancelledAt:'2026-09-19T17:00:00+07:00'});x.PemaCRM.run();assert(!task(x,'no_show',p.id));x.Pema.state.operations.appointments.at(-1).cancelledAt='2026-09-19T08:00:00+07:00';x.PemaCRM.run();assert(task(x,'no_show',p.id));});
check('cancel booked appointment returns expected visit to saved recommendation',()=>{const x=boot();x.PemaOps.saveAppointment({patient:'P027',service:'S0',doctor:'D0',room:'R0',date:'2026-09-27',time:'10:00'});const a=x.Pema.state.operations.appointments.at(-1);assert.equal(x.PemaCRM.profile(x.Pema.patient('P027')).overdueDays,0);x.PemaOps.cancel(a.id,'Khách chưa thu xếp được');x.PemaCRM.ensure();assert.equal(x.PemaCRM.profile(x.Pema.patient('P027')).overdueDays,14);});
const out=path.join(__dirname,'../demo-assets/screenshots/crm01');fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'crm-domain-results.json'),JSON.stringify({clock:'2026-09-20',checks:results},null,2));console.log(JSON.stringify({passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass)},null,2));if(results.some(x=>!x.pass))process.exitCode=1;
