"""Build the browser catalog from XLSX using only Python's standard library."""
import argparse
import hashlib
import json
from pathlib import Path
import xml.etree.ElementTree as ET
from zipfile import ZipFile

ROOT = Path(__file__).resolve().parent
NS = {'s': 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'}


def read_catalog(source):
    with ZipFile(source) as archive:
        strings = []
        if 'xl/sharedStrings.xml' in archive.namelist():
            strings = [''.join(n.itertext()) for n in ET.fromstring(archive.read('xl/sharedStrings.xml')).findall('s:si', NS)]
        sheet = ET.fromstring(archive.read('xl/worksheets/sheet1.xml'))
        rows, codes = [], set()
        for row in sheet.findall('s:sheetData/s:row', NS):
            cells = {}
            for cell in row.findall('s:c', NS):
                col = ''.join(c for c in cell.attrib['r'] if c.isalpha())
                value = cell.find('s:v', NS)
                raw = value.text if value is not None else ''
                if cell.get('t') == 's':
                    raw = strings[int(raw)]
                elif cell.get('t') == 'inlineStr':
                    raw = ''.join(cell.find('s:is', NS).itertext())
                cells[col] = raw or ''
            if int(row.attrib['r']) == 1:
                if [cells.get(k) for k in 'BCDEH'] != ['Mã', 'Tên', 'Đơn vị', 'Loại', 'Giá bán sau thuế']:
                    raise ValueError('Không đúng cột catalog: Mã, Tên, Đơn vị, Loại, Giá bán sau thuế')
                continue
            if not any(cells.get(k) for k in 'BCDE'):
                continue
            code = cells.get('B', '').strip().upper()
            name, kind = cells.get('C', '').strip(), cells.get('E', '').strip()
            if not code or not name or code in codes:
                raise ValueError(f'Dòng {row.attrib["r"]}: thiếu dữ liệu hoặc trùng mã {code}')
            price = float(cells.get('H') or 0)
            if not price.is_integer() or price < 0:
                raise ValueError(f'Giá không hợp lệ: {code}')
            codes.add(code)
            rows.append(dict(id='PRD-' + code, code=code, name=name, unit=cells.get('D', ''),
                             sourceType=kind, rowNumber=int(row.attrib['r']), vat=float(cells.get('F') or 0),
                             price=int(price), priceBeforeTax=float(cells.get('G') or 0),
                             batch=cells.get('J', ''), serial=cells.get('K', ''),
                             outputType=('PRESCRIPTION' if kind.casefold() == 'thuốc' else 'CONSULTATION') if kind else 'UNRESOLVED'))
        if not rows:
            raise ValueError('Catalog trống')
        return rows


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('source', nargs='?', type=Path, default=ROOT.parent / 'data/danhsach.xlsx')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    rows = read_catalog(args.source)
    metadata = dict(filename=args.source.name, sha256=hashlib.sha256(args.source.read_bytes()).hexdigest(),
                    totalRows=len(rows), prescription=sum(r['outputType'] == 'PRESCRIPTION' for r in rows))
    runtime = (ROOT / 'shared/product-catalog-runtime.js').read_text(encoding='utf-8')
    outputs = {
        'product-catalog.json': json.dumps(rows, ensure_ascii=False, indent=2) + '\n',
        'product-catalog.js': '// Generated by import-product-catalog.py; do not edit.\n(() => {\nconst rows = ' + json.dumps(rows, ensure_ascii=False) + ';\nconst source = ' + json.dumps(metadata, ensure_ascii=False) + ';\n' + runtime + '\n})();\n'
    }
    for name, content in outputs.items():
        path = ROOT / 'shared' / name
        if args.check:
            if path.read_text(encoding='utf-8') != content:
                raise SystemExit(f'Catalog differs from XLSX: {name}')
        else:
            path.write_text(content, encoding='utf-8')
    print(json.dumps(metadata))


if __name__ == '__main__':
    main()
