"""Where the bytes of a clinical photo live: a port and a local-volume adapter (package U, step U3).

New module (the old web kept images as data URLs in ``localStorage``). ``docs/ARCH-PB01.md``:
"Chuyển media khỏi
localStorage sang object storage với consent/retention". The port is the seam to object storage later; the
adapter below writes under one directory of the volume (``<data_dir>/clinic-media``). The database row
(``clinic.media``) is the record of an image; this module only stores and returns bytes by key.

Nothing here opens, decodes, resizes or analyses an image (PLAN-AI01-U principle 6): ``put`` takes bytes and
writes them, ``get`` returns them. A key is generated by the action (``patients/<patient id>/<media id>``) and
is checked here as well, so a caller can never reach outside the root.
"""

from __future__ import annotations

import asyncio
import re
from pathlib import Path
from typing import Final, Protocol, runtime_checkable

_KEY_PATTERN: Final = re.compile(r"^[a-z0-9][a-z0-9_-]*(/[a-z0-9][a-z0-9_.-]*)*$")
MAX_KEY_LENGTH: Final = 200


class MediaStorageError(Exception):
    """The storage could not do what was asked (bad key, missing object)."""


@runtime_checkable
class MediaStorage(Protocol):
    async def put(self, key: str, data: bytes) -> None: ...

    async def get(self, key: str) -> bytes:
        """The bytes of ``key``; raises ``MediaStorageError`` when there is no such object."""
        ...

    async def exists(self, key: str) -> bool: ...

    async def delete(self, key: str) -> None:
        """Remove ``key``; a missing object is not an error."""
        ...


def check_key(key: str) -> str:
    """The key itself when it is a safe relative path of lower-case segments, else ``MediaStorageError``."""
    if len(key) > MAX_KEY_LENGTH or ".." in key or _KEY_PATTERN.fullmatch(key) is None:
        raise MediaStorageError("invalid media key")
    return key


class LocalVolumeMediaStorage:
    """Files under ``root``. IO runs in a worker thread so the event loop is never blocked by a disk."""

    def __init__(self, root: Path) -> None:
        self._root = root

    def _path(self, key: str) -> Path:
        path = (self._root / check_key(key)).resolve()
        if not path.is_relative_to(self._root.resolve()):
            raise MediaStorageError("invalid media key")
        return path

    async def put(self, key: str, data: bytes) -> None:
        path = self._path(key)

        def write() -> None:
            path.parent.mkdir(parents=True, exist_ok=True)
            partial = path.with_name(path.name + ".part")
            partial.write_bytes(data)
            partial.replace(path)

        await asyncio.to_thread(write)

    async def get(self, key: str) -> bytes:
        path = self._path(key)

        def read() -> bytes:
            try:
                return path.read_bytes()
            except FileNotFoundError as exc:
                raise MediaStorageError("media object not found") from exc

        return await asyncio.to_thread(read)

    async def exists(self, key: str) -> bool:
        path = self._path(key)
        return await asyncio.to_thread(path.is_file)

    async def delete(self, key: str) -> None:
        path = self._path(key)
        await asyncio.to_thread(path.unlink, True)


class InMemoryMediaStorage:
    """Test double: the same contract, nothing on disk."""

    def __init__(self) -> None:
        self.objects: dict[str, bytes] = {}

    async def put(self, key: str, data: bytes) -> None:
        self.objects[check_key(key)] = data

    async def get(self, key: str) -> bytes:
        try:
            return self.objects[check_key(key)]
        except KeyError as exc:
            raise MediaStorageError("media object not found") from exc

    async def exists(self, key: str) -> bool:
        return check_key(key) in self.objects

    async def delete(self, key: str) -> None:
        self.objects.pop(check_key(key), None)
