// Tests of the zca-js adapter with a fake `Zalo` class: no login page is fetched, no QR is requested.
// They pin the two facts verified in zca-js 2.1.2 that differ from the original's comments (expired QR is
// not regenerated by the library; a declined QR never settles the promise).
import assert from "node:assert/strict";
import { describe, it } from "node:test";
import {
  LoginQRCallbackEventType,
  type API,
  type Credentials,
  type LoginQRCallback,
  type LoginQRCallbackEvent,
} from "zca-js";
import {
  exportCredentialFromApi,
  loginWithCredentials,
  loginWithQRForWeb,
  type ZaloLike,
} from "./zalo-client.js";
import { TEST_CREDENTIAL } from "./test-support.js";
import type { QrLoginEvent } from "./zalo-types.js";

/** The slice of a logged-in `API` that `toSession` reads; the cast is the single place a fake API is built. */
function fakeLoggedInApi(uid = "1000007"): API {
  return {
    getOwnId: () => uid,
    getContext: () => ({
      imei: "synthetic-imei",
      userAgent: "synthetic-agent",
      cookie: { toJSON: () => ({ cookies: [{ key: "zpsid", value: "synthetic" }] }) },
    }),
  } as unknown as API;
}

describe("loginWithCredentials", () => {
  it("the_credential_goes_to_zca_js_login_and_the_session_exposes_the_own_id", async () => {
    const received: Credentials[] = [];
    const zalo: ZaloLike = {
      login: async (credentials) => {
        received.push(credentials);
        return fakeLoggedInApi("1000042");
      },
      loginQR: async () => fakeLoggedInApi(),
    };

    const session = await loginWithCredentials(TEST_CREDENTIAL, () => zalo);

    assert.deepEqual(received, [TEST_CREDENTIAL]);
    assert.equal(session.ownId, "1000042");
  });

  it("a_login_failure_reaches_the_caller", async () => {
    const zalo: ZaloLike = {
      login: async () => {
        throw new Error("cookie rejected");
      },
      loginQR: async () => fakeLoggedInApi(),
    };
    await assert.rejects(
      loginWithCredentials(TEST_CREDENTIAL, () => zalo),
      /cookie rejected/,
    );
  });
});

describe("exportCredentialFromApi", () => {
  it("cookie_imei_and_user_agent_are_read_from_the_context", () => {
    assert.deepEqual(exportCredentialFromApi(fakeLoggedInApi()), {
      cookie: [{ key: "zpsid", value: "synthetic" }],
      imei: "synthetic-imei",
      userAgent: "synthetic-agent",
    });
  });
});

type QrHarness = {
  zalo: ZaloLike;
  events: QrLoginEvent[];
  calls: { retry: number; abort: number };
  fire(event: LoginQRCallbackEvent): void;
  finish(): void;
  fail(error: Error): void;
  callback(): LoginQRCallback;
};

function qrHarness(): QrHarness {
  const state = {
    callback: null as LoginQRCallback | null,
    resolve: (_api: API): void => undefined,
    reject: (_error: Error): void => undefined,
  };
  const zalo: ZaloLike = {
    login: async () => fakeLoggedInApi(),
    loginQR: (_options, callback) => {
      state.callback = callback ?? null;
      return new Promise<API>((resolve, reject) => {
        state.resolve = resolve;
        state.reject = reject;
      });
    },
  };
  const calls = { retry: 0, abort: 0 };
  return {
    zalo,
    events: [],
    calls,
    fire: (event) => void state.callback?.(event),
    finish: () => state.resolve(fakeLoggedInApi("1000099")),
    fail: (error) => state.reject(error),
    callback: () => {
      assert.ok(state.callback);
      return state.callback;
    },
  };
}

const actions = (calls: { retry: number; abort: number }) => ({
  retry: () => void (calls.retry += 1),
  abort: () => void (calls.abort += 1),
});

const generated = (
  calls: { retry: number; abort: number },
  image = "QR_BASE64",
): LoginQRCallbackEvent => ({
  type: LoginQRCallbackEventType.QRCodeGenerated,
  data: {
    code: "c",
    image,
    options: { enabledCheckOCR: false, enabledMultiLayer: false },
    token: "t",
  },
  actions: { saveToFile: async () => undefined, ...actions(calls) },
});

describe("loginWithQRForWeb", () => {
  it("a_generated_qr_is_handed_over_as_raw_base64_without_touching_the_disk", () => {
    const h = qrHarness();
    void loginWithQRForWeb(
      (event) => h.events.push(event),
      new AbortController().signal,
      () => h.zalo,
    );

    h.fire(generated(h.calls, "AAA"));

    assert.deepEqual(h.events, [{ type: "qr", qrBase64: "AAA" }]);
  });

  it("an_expired_qr_is_regenerated_by_calling_retry_because_the_library_does_not", () => {
    const h = qrHarness();
    void loginWithQRForWeb(
      (event) => h.events.push(event),
      new AbortController().signal,
      () => h.zalo,
    );

    h.fire({ type: LoginQRCallbackEventType.QRCodeExpired, data: null, actions: actions(h.calls) });

    assert.deepEqual(h.events, [{ type: "expired" }]);
    assert.deepEqual(h.calls, { retry: 1, abort: 0 });
  });

  it("a_scanned_qr_is_reported_without_the_account_name_or_avatar", () => {
    const h = qrHarness();
    void loginWithQRForWeb(
      (event) => h.events.push(event),
      new AbortController().signal,
      () => h.zalo,
    );

    h.fire({
      type: LoginQRCallbackEventType.QRCodeScanned,
      data: { avatar: "https://example.test/a.png", display_name: "Người Thử" },
      actions: actions(h.calls),
    });

    assert.deepEqual(h.events, [{ type: "scanned" }]);
  });

  it("a_declined_qr_is_reported_and_the_login_is_aborted_so_the_promise_settles", () => {
    const h = qrHarness();
    void loginWithQRForWeb(
      (event) => h.events.push(event),
      new AbortController().signal,
      () => h.zalo,
    );

    h.fire({
      type: LoginQRCallbackEventType.QRCodeDeclined,
      data: { code: "c" },
      actions: actions(h.calls),
    });

    assert.deepEqual(h.events, [{ type: "declined" }]);
    assert.deepEqual(h.calls, { retry: 0, abort: 1 });
  });

  it("aborting_the_signal_aborts_the_login_of_the_latest_qr", () => {
    const h = qrHarness();
    const controller = new AbortController();
    void loginWithQRForWeb(
      (event) => h.events.push(event),
      controller.signal,
      () => h.zalo,
    );
    h.fire(generated(h.calls));

    controller.abort();

    assert.equal(h.calls.abort, 1);
  });

  it("after_the_signal_is_aborted_an_expiry_aborts_instead_of_asking_for_a_new_qr", () => {
    const h = qrHarness();
    const controller = new AbortController();
    void loginWithQRForWeb(
      (event) => h.events.push(event),
      controller.signal,
      () => h.zalo,
    );
    controller.abort();

    h.fire({ type: LoginQRCallbackEventType.QRCodeExpired, data: null, actions: actions(h.calls) });

    assert.deepEqual(h.calls, { retry: 0, abort: 1 });
    assert.deepEqual(h.events, []);
  });

  it("a_qr_generated_after_the_abort_is_never_shown", () => {
    const h = qrHarness();
    const controller = new AbortController();
    void loginWithQRForWeb(
      (event) => h.events.push(event),
      controller.signal,
      () => h.zalo,
    );
    controller.abort();

    h.fire(generated(h.calls));

    assert.deepEqual(h.events, []);
    assert.equal(h.calls.abort, 1);
  });

  it("the_login_info_event_carries_no_secret_into_the_web_flow", () => {
    const h = qrHarness();
    void loginWithQRForWeb(
      (event) => h.events.push(event),
      new AbortController().signal,
      () => h.zalo,
    );

    h.fire({
      type: LoginQRCallbackEventType.GotLoginInfo,
      data: { cookie: [], imei: "secret-imei", userAgent: "secret-agent" },
      actions: null,
    });

    assert.deepEqual(h.events, [{ type: "info" }]);
  });

  it("a_finished_login_resolves_to_a_session_with_the_own_id", async () => {
    const h = qrHarness();
    const pending = loginWithQRForWeb(
      (event) => h.events.push(event),
      new AbortController().signal,
      () => h.zalo,
    );

    h.finish();

    assert.equal((await pending).ownId, "1000099");
  });

  it("a_failed_login_rejects_with_the_library_error", async () => {
    const h = qrHarness();
    const pending = loginWithQRForWeb(
      (event) => h.events.push(event),
      new AbortController().signal,
      () => h.zalo,
    );

    h.fail(new Error("Cannot get scan result"));

    await assert.rejects(pending, /Cannot get scan result/);
  });
});
